# IQ on human - K4me3 vs K27me3

In [2]:
library(prego)
library(iceqream)
options(tidyverse.quiet = TRUE)
library(tidyverse)
library(purrr)
library(tgutil)
library(misha)
library(misha.ext)
library(glue)
library(here)
library(tgstat)

gsetroot(here("data/hg19"))
options(gmax.data.size = 1e+9)
source(here("code/model-utils.R"))

Loading required package: misha

Warning message in system("timedatectl", intern = TRUE):
“running command 'timedatectl' had status 1”
here() starts at /net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper_raw

In [3]:
setwd(here())

In [ ]:
#iq-hg19-5mc-vs-nothing-model_preds.tsv

In [64]:
#cgd_all <- fread(here("output/iq-hg19-5mc-vs-nothing-model_preds.tsv")) %>% arrange(chrom,start)

In [5]:
setwd(here())

In [6]:
cgd_all = fread( here("output/cgd_hg19_iq.tsv"), sep = "\t", quote = FALSE)

In [7]:
head(cgd_all)

  chrom start     end       id        l    es_k27_max es_k4_max es_k27_cov
1 chr1    9488701   9489371 5S_rRNA.1  670   5.00      25.60    0.00000000
2 chr1   41826605  41828380 5S_rRNA.2 1775 110.25      90.60    0.38202247
3 chr1   41831862  41832691 5S_rRNA.3  829  17.00      88.75    0.00000000
4 chr1   41847183  41849391 5S_rRNA.4 2208  29.45     117.05    0.05405405
5 chr1   41889237  41889828 5S_rRNA.5  591   0.00       2.00    0.00000000
6 chr1  117487141 117487793 5S_rRNA.6  652   2.00       0.00    0.00000000
  es_k4_cov es_biv_cov ⋯ l10_h1_k4_sum l10_h1_k27_sum pcg   txg   l500 f_out
1 0.0000000 0.00000000 ⋯ 5.104462      3.665230       FALSE FALSE TRUE  TRUE
2 0.0000000 0.33707865 ⋯ 6.128760      6.101676       FALSE FALSE TRUE FALSE
3 0.7619048 0.00000000 ⋯ 6.706934      4.651147       FALSE FALSE TRUE FALSE
4 0.8018018 0.01801802 ⋯ 6.573153      4.947160       FALSE FALSE TRUE FALSE
5 0.0000000 0.00000000 ⋯ 3.461428      3.321928       FALSE FALSE TRUE  TRUE
6 0.0000000 0.00000000 ⋯ 3.321928      3.508475       FALSE FALSE TRUE  TRUE
  txg_pcg   resp10 f_ambig tss_gene
1        NA NA     FALSE   5S_rRNA
2 0.1035574 NA      TRUE   5S_rRNA
3 0.4733907 NA      TRUE   5S_rRNA
4 0.3946410 NA      TRUE   5S_rRNA
5        NA NA     FALSE   5S_rRNA
6        NA NA     FALSE   5S_rRNA

In [8]:
dim(cgd_all)

[1] 34153    45

In [9]:
dim(cgd_all)

[1] 34153    45

In [10]:
test_chroms <- c("chr2", "chr8", "chr12", "chr18")
cgd_all <- cgd_all %>% mutate(orig_resp10 = resp10) %>% 
    mutate(type = case_when(
        l500 & !f_out & chrom %in% test_chroms ~ "test",
        l500 & !f_out & !chrom %in% test_chroms ~ "train",
        TRUE ~ "other"
    )) %>% 
    mutate(resp10 = txg_pcg)
cgd_all <- cgd_all %>%    
    arrange(tss_gene, chrom, start, end) %>%
    group_by(tss_gene) %>%
    mutate(id = paste0(tss_gene, ".", row_number())) %>%
    mutate(n = n()) %>%
    mutate(id = ifelse(n == 1, tss_gene, id)) %>%
    select(-n) %>%
    ungroup() %>%
    select(chrom:end, id, everything())  %>% 
    as.data.frame() 
rownames(cgd_all) <- cgd_all$id

In [11]:
cgd_all %>%
    count(type)

  type  n
1 other 20151
2 test   2470
3 train 11532

In [12]:
pred_threshold <- 0.25
pROC::coords(pROC::roc(cgd_all$resp5mc, cgd_all$pred), pred_threshold, ret = c("threshold", "sensitivity", "specificity"))

ERROR: Error in roc.default(cgd_all$resp5mc, cgd_all$pred): No valid data provided.

In [13]:
pwm5 <- readr::read_rds(here("output/pwm5_norm_hg19_iq.rds"))
pwm5_pad <- readr::read_rds(here("output/pwm5_pad_norm_hg19_iq.rds"))
pwm3 <- readr::read_rds(here("output/pwm3_norm_hg19_iq.rds"))
pwm3_pad <- readr::read_rds(here("output/pwm3_pad_norm_hg19_iq.rds"))
pwm_in <- readr::read_rds(here("output/pwm_in_norm_hg19_iq.rds"))
add_feats <- readr::read_rds(here("output/add_feats_hg19_iq.rds"))
add_feats_in <- readr::read_rds(here("output/add_feats_in_hg19_iq.rds"))

In [21]:
dim(cgd_all)

[1] 34153    45

In [14]:
f <- cgd_all$type %in% c("train", "test") & cgd_all$id %in% rownames(pwm5)  & cgd_all$id %in% rownames(pwm5_pad) & cgd_all$id %in% rownames(pwm3) & cgd_all$id %in% rownames(pwm3_pad) & cgd_all$id %in% rownames(add_feats)
sum(f)
cgd <- cgd_all[f, ]
pwm5 <- pwm5[cgd$id, ]
pwm5_pad <- pwm5_pad[cgd$id, ]
pwm3 <- pwm3[cgd$id, ]
pwm3_pad <- pwm3_pad[cgd$id, ]
add_feats <- add_feats[cgd$id, ]
add_feats_in <- add_feats_in[cgd$id, ]
pwm_in <- pwm_in[cgd$id, ]

[1] 14001

In [15]:
add_feats5 <- add_feats
colnames(add_feats5) <- gsub("_5$", "", colnames(add_feats5))
add_feats3 <- add_feats
colnames(add_feats3) <- gsub("_3$", "", colnames(add_feats3))
add_feats5_pad <- add_feats
colnames(add_feats5_pad) <- gsub("_5pad$", "", colnames(add_feats5_pad))
add_feats3_pad <- add_feats
colnames(add_feats3_pad) <- gsub("_3pad$", "", colnames(add_feats3_pad))

cgd5 <- cgd[, 1:4]
cgd5$start <- ifelse(cgd$tss_strand == 1, cgd$start, cgd$end - 600)
cgd5$end <- ifelse(cgd$tss_strand == 1, cgd$start + 600, cgd$end)

cgd5_pad <- cgd[, 1:4]
cgd5_pad$start <- ifelse(cgd$tss_strand == 1, cgd$start - 500, cgd$end)
cgd5_pad$end <- ifelse(cgd$tss_strand == 1, cgd$start, cgd$end + 500)

cgd3 <- cgd[, 1:4]
cgd3$start <- ifelse(cgd$tss_strand == 1, cgd$end - 600, cgd$start)
cgd3$end <- ifelse(cgd$tss_strand == 1, cgd$end, cgd$start + 600)

cgd3_pad <- cgd[, 1:4]
cgd3_pad$start <- ifelse(cgd$tss_strand == 1, cgd$end, cgd$start - 500)
cgd3_pad$end <- ifelse(cgd$tss_strand == 1, cgd$end + 500, cgd$start)

train_idxs <- which(cgd$type == "train")
test_idxs <- which(cgd$type == "test")

cgd5_oriented <- cgd5
cgd5_oriented$strand <- cgd$tss_strand
cgd5_oriented <- cgd5_oriented %>% select(chrom, start, end, strand, everything())

cgd5_pad_oriented <- cgd5_pad
cgd5_pad_oriented$strand <- cgd$tss_strand
cgd5_pad_oriented <- cgd5_pad_oriented %>% select(chrom, start, end, strand, everything())

cgd3_oriented <- cgd3
cgd3_oriented$strand <- cgd$tss_strand
cgd3_oriented <- cgd3_oriented %>% select(chrom, start, end, strand, everything())

cgd3_pad_oriented <- cgd3_pad
cgd3_pad_oriented$strand <- cgd$tss_strand
cgd3_pad_oriented <- cgd3_pad_oriented %>% select(chrom, start, end, strand, everything())

cgd_oriented <- cgd
cgd_oriented$strand <- cgd$tss_strand
cgd_oriented <- cgd_oriented %>% select(chrom, start, end, strand, everything())

fwrite(cgd_oriented, here("output/cgd_oriented_hg19_iq_second.tsv"), sep = "\t")

In [16]:
scenic_motifs <- grep("SCENIC\\.", colnames(pwm5), value = TRUE)
pwm5 <- pwm5[, !(colnames(pwm5) %in% scenic_motifs)]
pwm5_pad <- pwm5_pad[, !(colnames(pwm5_pad) %in% scenic_motifs)]
pwm3 <- pwm3[, !(colnames(pwm3) %in% scenic_motifs)]
pwm3_pad <- pwm3_pad[, !(colnames(pwm3_pad) %in% scenic_motifs)]

In [17]:
stopifnot(all(cgd$id == rownames(pwm5)))
stopifnot(all(cgd$id == rownames(pwm5_pad)))
stopifnot(all(cgd$id == rownames(pwm3)))
stopifnot(all(cgd$id == rownames(pwm3_pad)))
stopifnot(all(cgd$id == rownames(add_feats)))
stopifnot(all(cgd$id == rownames(add_feats_in)))

In [19]:
fwrite(cgd, here("output/cgd_hg19_iq_second.tsv"), sep = "\t")

## Run models

In [20]:
#new
suffix <- "_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg"
run_iq_regression(
    model_type = "5",
    cgd = cgd,
    test_idxs = test_idxs,
    train_idxs = train_idxs,
    suffix = suffix
)
run_iq_regression(
    model_type = "3",
    cgd = cgd,
    test_idxs = test_idxs,
    train_idxs = train_idxs,
    suffix = suffix
)
run_iq_regression(
    model_type = "5_pad",
    cgd = cgd,
    test_idxs = test_idxs,
    train_idxs = train_idxs,
    suffix = suffix
)
run_iq_regression(
    model_type = "3_pad",
    cgd = cgd,
    test_idxs = test_idxs,
    train_idxs = train_idxs,
    suffix = suffix
)

→ Computing sequence features

ℹ Seed: 60427

ℹ Training on 11531 intervals (82%) and testing on 2470 intervals (18%)

ℹ Saving the train and test indices to "/net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper_raw/output/iq_5_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg"

ℹ Learning prego motifs (de-novo motifs)

ℹ Extracting sequences...

ℹ Inferring 5 prego motifs...

ℹ Using 15 bins of size 40 bp

ℹ Running regression for 5 motifs



── Running first regression ──



ℹ Using 15 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Performing sampled optimization

ℹ Sampling 1 of the dataset

✔ Sampled 11530 rows from the data frame.

ℹ Sampling 0.1 of the dataset

✔ Sampled 1150 rows from the data frame.



── Generate candidate kmers



── Regress each candidate kmer on sampled data

ℹ Running regression on 10 candidate kmers

• Bidirectional: TRUE

• Spat bin size: 40

• Number of spatial bins 15

• Length of sequence: 600

• Min gap: 0

• Max gap: 1

• Kmer length: 8

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

ℹ Performing regression on full data

ℹ Using 15 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Motif is shorter than 15, extending with wildcards

ℹ Initializing regression with the following motif: "***GGGGCGGG****"

ℹ Running regression

• Motif length: 15

• Bidirectional: TRUE

• Spat min: 0

• Spat max: 600

• Spat bin size: 40

• Number of bins: 15

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

✔ Finished running regression. Consensus: "CG"

✔ R^2: 0.1219

ℹ Best motif: "***GGGGCGGG****", score (r2): 0.105742518803406



── Running regression #2 ──



ℹ Using 15 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Performing sampled optimization

ℹ Sampling 1 of the dataset

✔ Sampled 11530 rows from the data frame.

ℹ Sampling 0.1 of the dataset

✔ Sampled 1150 rows from the data frame.



── Generate candidate kmers

ℹ Could not find any kmer when using a threshold of 0.08. Trying with 0.04



── Regress each candidate kmer on sampled data

ℹ Running regression on 1 candidate kmers

• Bidirectional: TRUE

• Spat bin size: 40

• Number of spatial bins 15

• Length of sequence: 600

• Min gap: 0

• Max gap: 1

• Kmer length: 8

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

→ regressing with seed: "CGCA*GCGC"

→ "CGCA*GCGC", score (r2): 0.00967030735261574, validation score (r2): 5.85775895863067e-07

ℹ Performing regression on full data

ℹ Using 15 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Motif is shorter than 15, extending with wildcards

ℹ Initializing regression with the following motif: "***CGCA*GCGC***"

ℹ Running regression

• Motif length: 15

• Bidirectional: TRUE

• Spat min: 0

• Spat max: 600

• Spat bin size: 40

• Number of bins: 15

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

✔ Finished running regression. Consensus: "RMGCA*GCGC"

✔ R^2: 0.0078

ℹ Best motif: "***CGCA*GCGC***", score (r2): 5.85775895863067e-07

ℹ R2 for models 1 and 2: 0.129527658111408

ℹ Improvement in R2: 0.00760899608936236



── Running regression #3 ──



ℹ Using 15 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Performing sampled optimization

ℹ Sampling 1 of the dataset

✔ Sampled 11530 rows from the data frame.

ℹ Sampling 0.1 of the dataset

✔ Sampled 1150 rows from the data frame.



── Generate candidate kmers

ℹ Could not find any kmer when using a threshold of 0.08. Trying with 0.04



── Regress each candidate kmer on sampled data

ℹ Running regression on 1 candidate kmers

• Bidirectional: TRUE

• Spat bin size: 40

• Number of spatial bins 15

• Length of sequence: 600

• Min gap: 0

• Max gap: 1

• Kmer length: 8

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

→ regressing with seed: "AA*ATGGCG"

→ "AA*ATGGCG", score (r2): 0.0158770407109678, validation score (r2): 0.00834522609193484

ℹ Performing regression on full data

ℹ Using 15 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Motif is shorter than 15, extending with wildcards

ℹ Initializing regression with the following motif: "***AA*ATGGCG***"

ℹ Running regression

• Motif length: 15

• Bidirectional: TRUE

• Spat min: 0

• Spat max: 600

• Spat bin size: 40

• Number of bins: 15

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

✔ Finished running regression. Consensus: "ATGG"

✔ R^2: 0.0161

ℹ Best motif: "***AA*ATGGCG***", score (r2): 0.00834522609193484

ℹ R2 for models 1, 2, and 3: 0.143267154221953

ℹ Improvement in R2: 0.0137394961105447



── Running regression #4 ──



ℹ Using 15 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Performing sampled optimization

ℹ Sampling 1 of the dataset

✔ Sampled 11530 rows from the data frame.

ℹ Sampling 0.1 of the dataset

✔ Sampled 1150 rows from the data frame.



── Generate candidate kmers

ℹ Could not find any kmer when using a threshold of 0.08. Trying with 0.04



── Regress each candidate kmer on sampled data

ℹ Running regression on 1 candidate kmers

• Bidirectional: TRUE

• Spat bin size: 40

• Number of spatial bins 15

• Length of sequence: 600

• Min gap: 0

• Max gap: 1

• Kmer length: 8

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

→ regressing with seed: "ACCAGA*CT"

→ "ACCAGA*CT", score (r2): 0.00447580469766442, validation score (r2): 0.00118388755109846

ℹ Performing regression on full data

ℹ Using 15 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Motif is shorter than 15, extending with wildcards

ℹ Initializing regression with the following motif: "***ACCAGA*CT***"

ℹ Running regression

• Motif length: 15

• Bidirectional: TRUE

• Spat min: 0

• Spat max: 600

• Spat bin size: 40

• Number of bins: 15

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

✔ Finished running regression. Consensus: "ACCA*AYCT**R"

✔ R^2: 0.0021

ℹ Best motif: "***ACCAGA*CT***", score (r2): 0.00118388755109846

ℹ R2 for models 1, 2, 3, and 4: 0.145370561262483

ℹ Improvement in R2: 0.00210340704053011



── Running regression #5 ──



ℹ Using 15 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Performing sampled optimization

ℹ Sampling 1 of the dataset

✔ Sampled 11530 rows from the data frame.

ℹ Sampling 0.1 of the dataset

✔ Sampled 1150 rows from the data frame.



── Generate candidate kmers

ℹ Could not find any kmer when using a threshold of 0.08. Trying with 0.04



── Regress each candidate kmer on sampled data

ℹ Running regression on 1 candidate kmers

• Bidirectional: TRUE

• Spat bin size: 40

• Number of spatial bins 15

• Length of sequence: 600

• Min gap: 0

• Max gap: 1

• Kmer length: 8

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

→ regressing with seed: "ACTTCCGG"

→ "ACTTCCGG", score (r2): 0.0231739295009209, validation score (r2): 0.00255263118388808

ℹ Performing regression on full data

ℹ Using 15 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Motif is shorter than 15, extending with wildcards

ℹ Initializing regression with the following motif: "***ACTTCCGG****"

ℹ Running regression

• Motif length: 15

• Bidirectional: TRUE

• Spat min: 0

• Spat max: 600

• Spat bin size: 40

• Number of bins: 15

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

✔ Finished running regression. Consensus: "CTTCC"

✔ R^2: 0.0119

ℹ Best motif: "***ACTTCCGG****", score (r2): 0.00255263118388808

ℹ R2 for models 1, 2, 3, 4, and 5: 0.155287016387279

ℹ Improvement in R2: 0.00991645512479658

✔ Best model: model #1 (score of 0.121918662022046)

→ Saving the prego model to "/net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper_raw/output/iq_5_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg/prego_model.rds"

→ Regressing on train set

ℹ Number of peaks: 11531

→ Extracting sequences...

ℹ Calculating correlations between 3872 motif energies and ATAC difference...

ℹ Selected 68 (out of 3872) features with absolute correlation >= 0.15

ℹ Running first round of regression, # of features: 68

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
ℹ Taking 53 features with beta >= 0.01

ℹ Running second round of regression...

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
ℹ Clustering 53 features into 10 clusters...

ℹ Choosing top 10 features clusters

ℹ Features left: 53

ℹ Learning a model for each motif cluster...

ℹ Infering energies...

ℹ Running final regression, number of features: 108

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
✔ Finished running model. Number of non-zero coefficients: 107 (out of 108). R^2: 0.204440983772306

→ Matching e1

→ Matched with "HOMER.Sp1", PSSM correlation = 0.660494457727532

→ Matching JOLMA.ELK1_mono_full

→ Matched with "HOMER.ETS", PSSM correlation = 0.765282685845344

→ Matching HOCOMOCO.TYY1_MOUSE.H11MO.0.A

→ Matched with "HOMER.YY1", PSSM correlation = 0.81431641879816

→ Matching JASPAR.ZBTB7A

→ Matched with "HOMER.ETS1", PSSM correlation = 0.87186923533612

→ Matching JASPAR.btd

→ Matched with "HOMER.Egr2", PSSM correlation = 0.742436294162996

→ Matching JOLMA.KLF14_mono_DBD

→ Matched with "HOMER.Klf4", PSSM correlation = 0.813670564719117

→ Matching HOCOMOCO.ATF3_HUMAN.H11MO.0.A

→ Matched with "HOMER.CRE", PSSM correlation = 0.804690579718533

→ Matching HOMER.Elk4

→ Matched with "HOMER.ETS1", PSSM correlation = 0.883651252029852

→ Matching HOCOMOCO.KLF12_HUMAN.H11MO.0.C

→ Matched with "HOMER.Sp1", PSSM correlation = 0.91547374664879

→ Matching HOCOMOCO.E2F4_MOUSE.H11MO.0.A

→ Matched with "HOMER.E2F1", PSSM correlation = 0.78318579384703

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
ℹ Extracting sequences...

ℹ Computing motif energies for 2470 intervals and 14001 normalization intervals

ℹ Inferring the model on 2470 intervals



Number of motifs: 10

R^2 train: 0.204

R^2 test: 0.21



→ Saving the model to "/net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper_raw/output/iq_5_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg/iq_regression_model.rds"

ℹ Plotting 10 motifs

Warning message:
“The `<scale>` argument of `guides()` cannot be `FALSE`. Use "none" instead as
of ggplot2 3.3.4.
ℹ The deprecated feature was likely used in the ggseqlogo package.
  Please report the issue at <https://github.com/omarwagih/ggseqlogo/issues>.”
ℹ Plotting motif "ETS1.2"

ℹ Plotting motif "Sp1"

ℹ Plotting motif "ETS"

ℹ Plotting motif "YY1"

ℹ Plotting motif "Klf4"

ℹ Plotting motif "ETS1"

ℹ Plotting motif "Sp1.2"

ℹ Plotting motif "E2F1"

ℹ Plotting motif "CRE"

ℹ Plotting motif "Egr2"

ℹ Saving plot...

Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 44 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 38 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 36 rows containing missing values or values outside the scale range
(`geom_line()`).”
✔ Plot saved to /net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper_raw/output/iq_5_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg/iq_regression_model.pdf

→ Filtering the model

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
ℹ Using 1150 samples for filtering

ℹ R^2 of the full model: 0.142737963566353

ℹ Filtering features with R^2 < 5e-04 and bits < 1.75

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by Sp1.2 (-----ACG-------): 0.0101049437542761. Bits: 1.91087952029462

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by ETS (----CCGGAA-----): -8.04736009525076e-05. Bits: 4.24726680740089

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by YY1 (---A--ATGGC----): 0.01673317122472. Bits: 4.69712536512646

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by ETS1.2 (---C-GGAAGT----): -0.00508121964616043. Bits: 3.62273263669829

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by Egr2 (-GGGGGCGGA): 0.00232054936390547. Bits: 11.2589495458358

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by Klf4 (---GCCACGCCCA--): -0.000599969021678776. Bits: 7.23913932244582

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by CRE (GGTGACGTGA-): 0.00309376405016398. Bits: 9.09597700344603

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by ETS1 (---CCGGAAGT----): -0.00132776158500955. Bits: 4.92101863719443

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by Sp1 (---G-CCCGCCC---): 0.000131987301813186. Bits: 4.5484447566256

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by E2F1 (-GGGGGCGGGAA--): -0.00128893641504724. Bits: 10.3609798675915

ℹ Trying to remove the following features with R^2 < 5e-04: "ETS", "ETS1.2", "Klf4", "ETS1", "Sp1", and "E2F1"

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ Not removing "ETS1" (changed the R^2 by only 0.00226759611723715).

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ Removing "E2F1" changed the R^2 by -0.00107483670119285

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ Removing "Klf4" changed the R^2 by -0.000829354663665738

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ Not removing "ETS" (changed the R^2 by only 0.00101081116260474).

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ Not removing "Sp1" (changed the R^2 by only 0.00533190922474011).

ℹ Removed 0 features with bits < 1.75

ℹ Removed 3 features with R^2 < 5e-04

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
✔ After filtering: Number of non-zero coefficients: 96 (out of 96). R^2: 0.201072472925478. Number of models: 7

ℹ Extracting sequences...

ℹ Computing motif energies for 2470 intervals and 14001 normalization intervals

ℹ Inferring the model on 2470 intervals



Number of motifs: 7

R^2 train: 0.201

R^2 test: 0.208



→ Saving the model to "/net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper_raw/output/iq_5_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg/iq_regression_filtered_model.rds"

ℹ Plotting 7 motifs

ℹ Plotting motif "YY1"

ℹ Plotting motif "Sp1.2"

ℹ Plotting motif "CRE"

ℹ Plotting motif "Egr2"

ℹ Plotting motif "Sp1"

ℹ Plotting motif "ETS"

ℹ Plotting motif "ETS1"

ℹ Saving plot...

Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 38 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 36 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
✔ Plot saved to /net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper_raw/output/iq_5_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg/iq_regression_filtered_model.pdf

✔ Finished IQ regression



Run `plot_traj_model_report(traj_model)` to visualize the model features

Run `plot_prediction_scatter(traj_model)` to visualize the model predictions

<TrajectoryModel> with 7 motifs and 17 additional features

Slots include:
• @model: A GLM model object. Number of non-zero coefficients: 96
• @motif_models: A named list of motif models. Each element contains PSSM and
spatial model (7 models: "Sp1.2", "ETS", "YY1", "Egr2", "CRE", "ETS1", and
"Sp1")
• @additional_features: A data frame of additional features (17 features)
• @coefs: A data frame of coefficients (24 elements)
• @model_features: A matrix of the model features (logistic functions of the
motif models energies, dimensions: 14001x96)
• @normalized_energies: A matrix of normalized energies of the model features
(dimensions: 14001x7)
• @type: A vector the length of the number of peaks, indicating whether each
peak is a training ('train') or a prediction peak ('test')
• @diff_score: A numeric value representing the difference score the model was
trained on (14001 elements)
• @predicted_diff_score: A numeric value representing the predicted difference
score
• @initial_prego_models: A list of prego models used in the initial phase of
the algorithm (5 models)
• @peak_intervals: A data frame containing the peak intervals (14001 elements)
• @normalization_intervals: A data frame containing the intervals used for
energy normalization (14001 elements)
• @features_r2: A numeric vector of the added R^2 values for each feature (7
elements)
• @params: A list of parameters used for training (including:
"energy_norm_quantile", "norm_energy_max", "min_energy", "alpha", "lambda",
"peaks_size", "spat_num_bins", "spat_bin_size", "n_clust_factor",
"include_interactions", "interaction_threshold", "symmetrize_spat", "seed",
"names_map", "stats", "features_bits", "r2_threshold", and "bits_threshold")

R^2 train: 0.201
R^2 test: 0.208

→ Computing sequence features

ℹ Seed: 60427

ℹ Training on 11531 intervals (82%) and testing on 2470 intervals (18%)

ℹ Saving the train and test indices to "/net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper_raw/output/iq_3_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg"

ℹ Learning prego motifs (de-novo motifs)

ℹ Extracting sequences...

ℹ Inferring 5 prego motifs...

ℹ Using 15 bins of size 40 bp

ℹ Running regression for 5 motifs



── Running first regression ──



ℹ Using 15 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Performing sampled optimization

ℹ Sampling 1 of the dataset

✔ Sampled 11530 rows from the data frame.

ℹ Sampling 0.1 of the dataset

✔ Sampled 1150 rows from the data frame.



── Generate candidate kmers

ℹ Could not find any kmer when using a threshold of 0.08. Trying with 0.04



── Regress each candidate kmer on sampled data

ℹ Running regression on 1 candidate kmers

• Bidirectional: TRUE

• Spat bin size: 40

• Number of spatial bins 15

• Length of sequence: 600

• Min gap: 0

• Max gap: 1

• Kmer length: 8

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

→ regressing with seed: "GGGG*CGGG"

→ "GGGG*CGGG", score (r2): 0.107036274938829, validation score (r2): 0.0990299054837721

ℹ Performing regression on full data

ℹ Using 15 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Motif is shorter than 15, extending with wildcards

ℹ Initializing regression with the following motif: "***GGGG*CGGG***"

ℹ Running regression

• Motif length: 15

• Bidirectional: TRUE

• Spat min: 0

• Spat max: 600

• Spat bin size: 40

• Number of bins: 15

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

✔ Finished running regression. Consensus: "CG"

✔ R^2: 0.1066

ℹ Best motif: "***GGGG*CGGG***", score (r2): 0.0990299054837721



── Running regression #2 ──



ℹ Using 15 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Performing sampled optimization

ℹ Sampling 1 of the dataset

✔ Sampled 11530 rows from the data frame.

ℹ Sampling 0.1 of the dataset

✔ Sampled 1150 rows from the data frame.



── Generate candidate kmers

ℹ Could not find any kmer when using a threshold of 0.08. Trying with 0.04



── Regress each candidate kmer on sampled data

ℹ Running regression on 1 candidate kmers

• Bidirectional: TRUE

• Spat bin size: 40

• Number of spatial bins 15

• Length of sequence: 600

• Min gap: 0

• Max gap: 1

• Kmer length: 8

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

→ regressing with seed: "TGTA*TTAT"

→ "TGTA*TTAT", score (r2): 0.00283788528813068, validation score (r2): 0.00478780228375218

ℹ Performing regression on full data

ℹ Using 15 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Motif is shorter than 15, extending with wildcards

ℹ Initializing regression with the following motif: "***TGTA*TTAT***"

ℹ Running regression

• Motif length: 15

• Bidirectional: TRUE

• Spat min: 0

• Spat max: 600

• Spat bin size: 40

• Number of bins: 15

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

✔ Finished running regression. Consensus: "AATTAT"

✔ R^2: 0.0037

ℹ Best motif: "***TGTA*TTAT***", score (r2): 0.00478780228375218

ℹ R2 for models 1 and 2: 0.110707639864282

ℹ Improvement in R2: 0.00413677055476798



── Running regression #3 ──



ℹ Using 15 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Performing sampled optimization

ℹ Sampling 1 of the dataset

✔ Sampled 11530 rows from the data frame.

ℹ Sampling 0.1 of the dataset

✔ Sampled 1150 rows from the data frame.



── Generate candidate kmers

ℹ Could not find any kmer when using a threshold of 0.08. Trying with 0.04



── Regress each candidate kmer on sampled data

ℹ Running regression on 1 candidate kmers

• Bidirectional: TRUE

• Spat bin size: 40

• Number of spatial bins 15

• Length of sequence: 600

• Min gap: 0

• Max gap: 1

• Kmer length: 8

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

→ regressing with seed: "TCT*GAACC"

→ "TCT*GAACC", score (r2): 0.00291940085305419, validation score (r2): 0.00160970375223141

ℹ Performing regression on full data

ℹ Using 15 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Motif is shorter than 15, extending with wildcards

ℹ Initializing regression with the following motif: "***TCT*GAACC***"

ℹ Running regression

• Motif length: 15

• Bidirectional: TRUE

• Spat min: 0

• Spat max: 600

• Spat bin size: 40

• Number of bins: 15

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

✔ Finished running regression. Consensus: "TCT*GAACC"

✔ R^2: 0.0012

ℹ Best motif: "***TCT*GAACC***", score (r2): 0.00160970375223141

ℹ R2 for models 1, 2, and 3: 0.111876861255564

ℹ Improvement in R2: 0.00116922139128205



── Running regression #4 ──



ℹ Using 15 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Performing sampled optimization

ℹ Sampling 1 of the dataset

✔ Sampled 11530 rows from the data frame.

ℹ Sampling 0.1 of the dataset

✔ Sampled 1150 rows from the data frame.



── Generate candidate kmers

ℹ Could not find any kmer when using a threshold of 0.08. Trying with 0.04



── Regress each candidate kmer on sampled data

ℹ Running regression on 1 candidate kmers

• Bidirectional: TRUE

• Spat bin size: 40

• Number of spatial bins 15

• Length of sequence: 600

• Min gap: 0

• Max gap: 1

• Kmer length: 8

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

→ regressing with seed: "GCGCATGC"

→ "GCGCATGC", score (r2): 0.00046267467261157, validation score (r2): 0.000406775466097394

ℹ Performing regression on full data

ℹ Using 15 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Motif is shorter than 15, extending with wildcards

ℹ Initializing regression with the following motif: "***GCGCATGC****"

ℹ Running regression

• Motif length: 15

• Bidirectional: TRUE

• Spat min: 0

• Spat max: 600

• Spat bin size: 40

• Number of bins: 15

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

✔ Finished running regression. Consensus: "GCGCATGC"

✔ R^2: 2e-04

ℹ Best motif: "***GCGCATGC****", score (r2): 0.000406775466097394

ℹ R2 for models 1, 2, 3, and 4: 0.112181908522617

ℹ Improvement in R2: 0.000305047267052411



── Running regression #5 ──



ℹ Using 15 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Performing sampled optimization

ℹ Sampling 1 of the dataset

✔ Sampled 11530 rows from the data frame.

ℹ Sampling 0.1 of the dataset

✔ Sampled 1150 rows from the data frame.



── Generate candidate kmers

ℹ Could not find any kmer when using a threshold of 0.08. Trying with 0.04



── Regress each candidate kmer on sampled data

ℹ Running regression on 1 candidate kmers

• Bidirectional: TRUE

• Spat bin size: 40

• Number of spatial bins 15

• Length of sequence: 600

• Min gap: 0

• Max gap: 1

• Kmer length: 8

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

→ regressing with seed: "TCT*GAACC"

→ "TCT*GAACC", score (r2): 0.00208969531299561, validation score (r2): 0.00197500452485957

ℹ Performing regression on full data

ℹ Using 15 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Motif is shorter than 15, extending with wildcards

ℹ Initializing regression with the following motif: "***TCT*GAACC***"

ℹ Running regression

• Motif length: 15

• Bidirectional: TRUE

• Spat min: 0

• Spat max: 600

• Spat bin size: 40

• Number of bins: 15

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

✔ Finished running regression. Consensus: "WTCT**AACC"

✔ R^2: 5e-04

ℹ Best motif: "***TCT*GAACC***", score (r2): 0.00197500452485957

ℹ R2 for models 1, 2, 3, 4, and 5: 0.112673257659356

ℹ Improvement in R2: 0.000491349136739233

✔ Best model: model #1 (score of 0.106570869309514)

→ Saving the prego model to "/net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper_raw/output/iq_3_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg/prego_model.rds"

→ Regressing on train set

ℹ Number of peaks: 11531

→ Extracting sequences...

ℹ Calculating correlations between 3872 motif energies and ATAC difference...

! No features with absolute correlation >= 0.15. Trying again with 0.075

ℹ Selected 700 (out of 3872) features with absolute correlation >= 0.075

ℹ Running first round of regression, # of features: 700

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
ℹ Taking 466 features with beta >= 0.01

ℹ Running second round of regression...

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
ℹ Clustering 465 features into 10 clusters...

ℹ Choosing top 10 features clusters

ℹ Features left: 465

ℹ Learning a model for each motif cluster...

ℹ Infering energies...

ℹ Running final regression, number of features: 108

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
✔ Finished running model. Number of non-zero coefficients: 108 (out of 108). R^2: 0.265002347603524

→ Matching JOLMA.FEV_mono_DBD

→ Matched with "HOMER.GABPA", PSSM correlation = 0.893746775857918

→ Matching HOCOMOCO.THAP1_HUMAN.H11MO.0.C

→ Matched with "HOMER.Sp1", PSSM correlation = 0.530277985820149

→ Matching JOLMA.ESX1_mono_full

→ Matched with "HOMER.Lhx2", PSSM correlation = 0.666015882475656

→ Matching JASPAR.DAL82

→ Matched with "HOMER.NRF1", PSSM correlation = 0.832351352701554

→ Matching HOCOMOCO.SMAD2_MOUSE.H11MO.0.A

→ Matched with "HOMER.NF1_halfsite", PSSM correlation = 0.76640636920236

→ Matching HOCOMOCO.KLF1_HUMAN.H11MO.0.A

→ Matched with "HOMER.KLF5", PSSM correlation = 0.800590885929077

→ Matching JOLMA.YY1_mono_full

→ Matched with "HOMER.YY1", PSSM correlation = 0.902098360145579

→ Matching JASPAR.Atf1

→ Matched with "HOMER.Atf1", PSSM correlation = 0.691495849534117

→ Matching HOMER.bZIPIRF

→ Matched with "HOMER.GATA3_2", PSSM correlation = 0.849990845028042

→ Matching e5

→ Matched with "HOMER.Pit1", PSSM correlation = 0.505750431221846

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
ℹ Extracting sequences...

ℹ Computing motif energies for 2470 intervals and 14001 normalization intervals

ℹ Inferring the model on 2470 intervals



Number of motifs: 10

R^2 train: 0.265

R^2 test: 0.258



→ Saving the model to "/net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper_raw/output/iq_3_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg/iq_regression_model.rds"

ℹ Plotting 10 motifs

ℹ Plotting motif "Pit1"

ℹ Plotting motif "GABPA"

ℹ Plotting motif "YY1"

ℹ Plotting motif "KLF5"

ℹ Plotting motif "Sp1"

ℹ Plotting motif "Lhx2"

ℹ Plotting motif "NRF1"

ℹ Plotting motif "GATA3_2"

ℹ Plotting motif "NF1_halfsite"

ℹ Plotting motif "Atf1"

ℹ Saving plot...

Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
✔ Plot saved to /net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper_raw/output/iq_3_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg/iq_regression_model.pdf

→ Filtering the model

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
ℹ Using 1150 samples for filtering

ℹ R^2 of the full model: 0.206022000807689

ℹ Filtering features with R^2 < 5e-04 and bits < 1.75

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by GABPA (--CCGGAAG------): 0.00895984997760407. Bits: 4.23841650349289

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by Sp1 (-----CG--------): 0.00875678953082062. Bits: 2.11566522791985

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by Lhx2 (------TAAAT----): 0.0158253185634674. Bits: 3.97857073885636

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by NRF1 (--GCGCA-GCGC---): 0.00283062850333429. Bits: 11.3812440276032

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by NF1_halfsite (-------GCCAA---): 0.00135117176420285. Bits: 4.96952263386465

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by KLF5 (-G-GGGCGGA-C---): 0.00755315076676863. Bits: 8.94662810717021

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by YY1 (------ATGGC-G--): 0.0106379389362446. Bits: 4.43713191476873

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by Atf1 (---GTCACG------): 0.000185683705102885. Bits: 3.35587068161671

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by GATA3_2 (---AGATAA------): -0.000396551564513986. Bits: 3.49678452743172

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by Pit1 (---GGTTC-AGAA--): 0.00953227706390689. Bits: 8.64151117355903

ℹ Trying to remove the following features with R^2 < 5e-04: "Atf1" and "GATA3_2"

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ Not removing "Atf1" (changed the R^2 by only 0.00121710021800672).

ℹ Removed 0 features with bits < 1.75

ℹ Removed 1 features with R^2 < 5e-04

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
✔ After filtering: Number of non-zero coefficients: 103 (out of 104). R^2: 0.261088595215155. Number of models: 9

ℹ Extracting sequences...

ℹ Computing motif energies for 2470 intervals and 14001 normalization intervals

ℹ Inferring the model on 2470 intervals



Number of motifs: 9

R^2 train: 0.261

R^2 test: 0.256



→ Saving the model to "/net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper_raw/output/iq_3_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg/iq_regression_filtered_model.rds"

ℹ Plotting 9 motifs

ℹ Plotting motif "Lhx2"

ℹ Plotting motif "YY1"

ℹ Plotting motif "Pit1"

ℹ Plotting motif "GABPA"

ℹ Plotting motif "Sp1"

ℹ Plotting motif "KLF5"

ℹ Plotting motif "NRF1"

ℹ Plotting motif "NF1_halfsite"

ℹ Plotting motif "Atf1"

ℹ Saving plot...

Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”

Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
✔ Plot saved to /net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper_raw/output/iq_3_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg/iq_regression_filtered_model.pdf

✔ Finished IQ regression



Run `plot_traj_model_report(traj_model)` to visualize the model features

Run `plot_prediction_scatter(traj_model)` to visualize the model predictions

<TrajectoryModel> with 9 motifs and 17 additional features

Slots include:
• @model: A GLM model object. Number of non-zero coefficients: 103
• @motif_models: A named list of motif models. Each element contains PSSM and
spatial model (9 models: "GABPA", "Sp1", "Lhx2", "NRF1", "NF1_halfsite",
"KLF5", "YY1", "Atf1", and "Pit1")
• @additional_features: A data frame of additional features (17 features)
• @coefs: A data frame of coefficients (26 elements)
• @model_features: A matrix of the model features (logistic functions of the
motif models energies, dimensions: 14001x104)
• @normalized_energies: A matrix of normalized energies of the model features
(dimensions: 14001x9)
• @type: A vector the length of the number of peaks, indicating whether each
peak is a training ('train') or a prediction peak ('test')
• @diff_score: A numeric value representing the difference score the model was
trained on (14001 elements)
• @predicted_diff_score: A numeric value representing the predicted difference
score
• @initial_prego_models: A list of prego models used in the initial phase of
the algorithm (5 models)
• @peak_intervals: A data frame containing the peak intervals (14001 elements)
• @normalization_intervals: A data frame containing the intervals used for
energy normalization (14001 elements)
• @features_r2: A numeric vector of the added R^2 values for each feature (9
elements)
• @params: A list of parameters used for training (including:
"energy_norm_quantile", "norm_energy_max", "min_energy", "alpha", "lambda",
"peaks_size", "spat_num_bins", "spat_bin_size", "n_clust_factor",
"include_interactions", "interaction_threshold", "symmetrize_spat", "seed",
"names_map", "stats", "features_bits", "r2_threshold", and "bits_threshold")

R^2 train: 0.261
R^2 test: 0.256

→ Computing sequence features

ℹ Seed: 60427

ℹ Training on 11531 intervals (82%) and testing on 2470 intervals (18%)

ℹ Saving the train and test indices to "/net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper_raw/output/iq_5_pad_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg"

ℹ Learning prego motifs (de-novo motifs)

ℹ Extracting sequences...

ℹ Inferring 5 prego motifs...

ℹ Using 11 bins of size 40 bp

ℹ Running regression for 5 motifs



── Running first regression ──



ℹ Using 11 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Performing sampled optimization

ℹ Sampling 1 of the dataset

✔ Sampled 11530 rows from the data frame.

ℹ Sampling 0.1 of the dataset

✔ Sampled 1150 rows from the data frame.



── Generate candidate kmers



── Regress each candidate kmer on sampled data

ℹ Running regression on 10 candidate kmers

• Bidirectional: TRUE

• Spat bin size: 40

• Number of spatial bins 11

• Length of sequence: 440

• Min gap: 0

• Max gap: 1

• Kmer length: 8

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

ℹ Performing regression on full data

ℹ Using 11 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Motif is shorter than 15, extending with wildcards

ℹ Initializing regression with the following motif: "***TGGGA*TAC***"

ℹ Running regression

• Motif length: 15

• Bidirectional: TRUE

• Spat min: 30

• Spat max: 470

• Spat bin size: 40

• Number of bins: 11

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

✔ Finished running regression. Consensus: NA

✔ R^2: 0.087

ℹ Best motif: "***TGGGA*TAC***", score (r2): 0.0609615259368802



── Running regression #2 ──



ℹ Using 11 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Performing sampled optimization

ℹ Sampling 1 of the dataset

✔ Sampled 11530 rows from the data frame.

ℹ Sampling 0.1 of the dataset

✔ Sampled 1150 rows from the data frame.



── Generate candidate kmers

ℹ Could not find any kmer when using a threshold of 0.08. Trying with 0.04



── Regress each candidate kmer on sampled data

ℹ Running regression on 1 candidate kmers

• Bidirectional: TRUE

• Spat bin size: 40

• Number of spatial bins 11

• Length of sequence: 440

• Min gap: 0

• Max gap: 1

• Kmer length: 8

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

→ regressing with seed: "GCTCTGCG"

→ "GCTCTGCG", score (r2): 0.00312626358094929, validation score (r2): 0.00010495290301675

ℹ Performing regression on full data

ℹ Using 11 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Motif is shorter than 15, extending with wildcards

ℹ Initializing regression with the following motif: "***GCTCTGCG****"

ℹ Running regression

• Motif length: 15

• Bidirectional: TRUE

• Spat min: 30

• Spat max: 470

• Spat bin size: 40

• Number of bins: 11

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

✔ Finished running regression. Consensus: "G*TCTGCG"

✔ R^2: 0.003

ℹ Best motif: "***GCTCTGCG****", score (r2): 0.00010495290301675

ℹ R2 for models 1 and 2: 0.0907566136790458

ℹ Improvement in R2: 0.00373889903006905



── Running regression #3 ──



ℹ Using 11 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Performing sampled optimization

ℹ Sampling 1 of the dataset

✔ Sampled 11530 rows from the data frame.

ℹ Sampling 0.1 of the dataset

✔ Sampled 1150 rows from the data frame.



── Generate candidate kmers

ℹ Could not find any kmer when using a threshold of 0.08. Trying with 0.04



── Regress each candidate kmer on sampled data

ℹ Running regression on 1 candidate kmers

• Bidirectional: TRUE

• Spat bin size: 40

• Number of spatial bins 11

• Length of sequence: 440

• Min gap: 0

• Max gap: 1

• Kmer length: 8

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

→ regressing with seed: "AAT*ACCCC"

→ "AAT*ACCCC", score (r2): 0.00531786064823419, validation score (r2): 0.00115193897782444

ℹ Performing regression on full data

ℹ Using 11 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Motif is shorter than 15, extending with wildcards

ℹ Initializing regression with the following motif: "***AAT*ACCCC***"

ℹ Running regression

• Motif length: 15

• Bidirectional: TRUE

• Spat min: 30

• Spat max: 470

• Spat bin size: 40

• Number of bins: 11

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

✔ Finished running regression. Consensus: "AAT*ACC*C"

✔ R^2: 0.006

ℹ Best motif: "***AAT*ACCCC***", score (r2): 0.00115193897782444

ℹ R2 for models 1, 2, and 3: 0.0958341326627046

ℹ Improvement in R2: 0.00507751898365887



── Running regression #4 ──



ℹ Using 11 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Performing sampled optimization

ℹ Sampling 1 of the dataset

✔ Sampled 11530 rows from the data frame.

ℹ Sampling 0.1 of the dataset

✔ Sampled 1150 rows from the data frame.



── Generate candidate kmers

ℹ Could not find any kmer when using a threshold of 0.08. Trying with 0.04



── Regress each candidate kmer on sampled data

ℹ Running regression on 1 candidate kmers

• Bidirectional: TRUE

• Spat bin size: 40

• Number of spatial bins 11

• Length of sequence: 440

• Min gap: 0

• Max gap: 1

• Kmer length: 8

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

→ regressing with seed: "GGAGGT*CC"

→ "GGAGGT*CC", score (r2): 0.000701745416447046, validation score (r2): 4.5788038619567e-05

ℹ Performing regression on full data

ℹ Using 11 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Motif is shorter than 15, extending with wildcards

ℹ Initializing regression with the following motif: "***GGAGGT*CC***"

ℹ Running regression

• Motif length: 15

• Bidirectional: TRUE

• Spat min: 30

• Spat max: 470

• Spat bin size: 40

• Number of bins: 11

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

✔ Finished running regression. Consensus: "GGAGGT*CC"

✔ R^2: 5e-04

ℹ Best motif: "***GGAGGT*CC***", score (r2): 4.5788038619567e-05

ℹ R2 for models 1, 2, 3, and 4: 0.0967399408240369

ℹ Improvement in R2: 0.000905808161332247



── Running regression #5 ──



ℹ Using 11 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Performing sampled optimization

ℹ Sampling 1 of the dataset

✔ Sampled 11530 rows from the data frame.

ℹ Sampling 0.1 of the dataset

✔ Sampled 1150 rows from the data frame.



── Generate candidate kmers

ℹ Could not find any kmer when using a threshold of 0.08. Trying with 0.04



── Regress each candidate kmer on sampled data

ℹ Running regression on 1 candidate kmers

• Bidirectional: TRUE

• Spat bin size: 40

• Number of spatial bins 11

• Length of sequence: 440

• Min gap: 0

• Max gap: 1

• Kmer length: 8

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

→ regressing with seed: "GCGACTGT"

→ "GCGACTGT", score (r2): 0.000804888658348006, validation score (r2): 1.03735206601707e-06

ℹ Performing regression on full data

ℹ Using 11 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Motif is shorter than 15, extending with wildcards

ℹ Initializing regression with the following motif: "***GCGACTGT****"

ℹ Running regression

• Motif length: 15

• Bidirectional: TRUE

• Spat min: 30

• Spat max: 470

• Spat bin size: 40

• Number of bins: 11

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

✔ Finished running regression. Consensus: "GCGACTGT**R"

✔ R^2: 8e-04

ℹ Best motif: "***GCGACTGT****", score (r2): 1.03735206601707e-06

ℹ R2 for models 1, 2, 3, 4, and 5: 0.0974703506648913

ℹ Improvement in R2: 0.000730409840854387

✔ Best model: model #1 (score of 0.0870177146489767)

→ Saving the prego model to "/net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper_raw/output/iq_5_pad_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg/prego_model.rds"

→ Regressing on train set

ℹ Number of peaks: 11531

→ Extracting sequences...

ℹ Calculating correlations between 3872 motif energies and ATAC difference...

! No features with absolute correlation >= 0.2. Trying again with 0.1

ℹ Selected 1346 (out of 3872) features with absolute correlation >= 0.1

ℹ Running first round of regression, # of features: 1346

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
ℹ Taking 831 features with beta >= 0.01

ℹ Running second round of regression...

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
ℹ Clustering 828 features into 10 clusters...

ℹ Choosing top 10 features clusters

ℹ Features left: 828

ℹ Learning a model for each motif cluster...

ℹ Infering energies...

ℹ Running final regression, number of features: 108

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
✔ Finished running model. Number of non-zero coefficients: 108 (out of 108). R^2: 0.137726791073488

→ Matching JOLMA.HOXB13_mono_DBD_1

→ Matched with "HOMER.GSC", PSSM correlation = 0.570956987547146

→ Matching JASPAR.FOSL1::JUND.MA1142.1

→ Matched with "HOMER.Jun_AP1", PSSM correlation = 0.815354462760487

→ Matching HOCOMOCO.KLF3_MOUSE.H11MO.0.A

→ Matched with "HOMER.KLF5", PSSM correlation = 0.882751089828118

→ Matching JOLMA.DPRX_mono_DBD_1

→ Matched with "HOMER.GSC", PSSM correlation = 0.641717386086804

→ Matching HOCOMOCO.ZIC2_MOUSE.H11MO.0.C

→ Matched with "HOMER.ETS1", PSSM correlation = 0.557760576267912

→ Matching HOMER.Atf1

→ Matched with "HOMER.JunD", PSSM correlation = 0.863181946933636

→ Matching JASPAR.ARF39

→ Matched with "HOMER.Klf4", PSSM correlation = 0.552868202937128

→ Matching JASPAR.MEF2D

→ Matched with "HOMER.TEAD2", PSSM correlation = 0.711868958325568

→ Matching JASPAR.SREBF2.MA0828.2

→ Matched with "HOMER.MyoG", PSSM correlation = 0.501745935485428

→ Matching JASPAR.ZNF574

→ Matched with "HOMER.Meis1", PSSM correlation = 0.590852961934174

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
ℹ Extracting sequences...

ℹ Computing motif energies for 2470 intervals and 14001 normalization intervals

ℹ Inferring the model on 2470 intervals



Number of motifs: 10

R^2 train: 0.138

R^2 test: 0.18



→ Saving the model to "/net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper_raw/output/iq_5_pad_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg/iq_regression_model.rds"

ℹ Plotting 10 motifs

ℹ Plotting motif "Meis1"

ℹ Plotting motif "MyoG"

ℹ Plotting motif "Jun_AP1"

ℹ Plotting motif "Klf4"

ℹ Plotting motif "GSC"

ℹ Plotting motif "KLF5"

ℹ Plotting motif "GSC.2"

ℹ Plotting motif "JunD"

ℹ Plotting motif "TEAD2"

ℹ Plotting motif "ETS1"

ℹ Saving plot...

Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
✔ Plot saved to /net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper_raw/output/iq_5_pad_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg/iq_regression_model.pdf

→ Filtering the model

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
ℹ Using 1150 samples for filtering

ℹ R^2 of the full model: 0.0751987778163116

ℹ Filtering features with R^2 < 5e-04 and bits < 1.75

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by GSC.2 (-----T-A-------): 0.00100261746751967. Bits: 1.01434602523677

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by Jun_AP1 (---TGACTCA-----): 0.000613926641782947. Bits: 3.59549146122894

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by KLF5 (----GGGCG------): 0.00133340334779458. Bits: 4.66686097332569

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by GSC (-----GGGATTA---): -0.00141910864159378. Bits: 4.47255242712528

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by ETS1 (---GGAGGT-CC---): -0.000451958977188277. Bits: 2.73623909886248

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by JunD (--G-TGACGT-A---): 0.000471079437178695. Bits: 3.88172230410846

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by Klf4 (---CCCC-C------): -0.00112144001239949. Bits: 3.11156762179441

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by TEAD2 (-----AG-AAT----): 0.000500158073030152. Bits: 2.66614120947567

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
→ R^2 added by MyoG (-GCC-AGGC-A-A-A): 0.00784298960445863. Bits: 4.14527640537453

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by Meis1 (----CAGA-A-----): 0.00165124180742746. Bits: 2.15643447352518

ℹ Removing the following features with bits < 1.75: "GSC.2"

ℹ Trying to remove the following features with R^2 < 5e-04: "GSC", "ETS1", "JunD", and "Klf4"

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ Removing "Klf4" changed the R^2 by -0.000746891137783576

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ Removing "ETS1" changed the R^2 by -1.65498571228079e-05

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ Not removing "JunD" (changed the R^2 by only 0.00136408578755071).

ℹ Removed 1 features with bits < 1.75

ℹ Removed 3 features with R^2 < 5e-04

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
✔ After filtering: Number of non-zero coefficients: 92 (out of 92). R^2: 0.124323993969668. Number of models: 6

ℹ Extracting sequences...

ℹ Computing motif energies for 2470 intervals and 14001 normalization intervals

ℹ Inferring the model on 2470 intervals



Number of motifs: 6

R^2 train: 0.124

R^2 test: 0.175



→ Saving the model to "/net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper_raw/output/iq_5_pad_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg/iq_regression_filtered_model.rds"

ℹ Plotting 6 motifs

ℹ Plotting motif "MyoG"

ℹ Plotting motif "Meis1"

ℹ Plotting motif "KLF5"

ℹ Plotting motif "Jun_AP1"

ℹ Plotting motif "TEAD2"

ℹ Plotting motif "JunD"

ℹ Saving plot...

Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
✔ Plot saved to /net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper_raw/output/iq_5_pad_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg/iq_regression_filtered_model.pdf

✔ Finished IQ regression



Run `plot_traj_model_report(traj_model)` to visualize the model features

Run `plot_prediction_scatter(traj_model)` to visualize the model predictions

<TrajectoryModel> with 6 motifs and 17 additional features

Slots include:
• @model: A GLM model object. Number of non-zero coefficients: 92
• @motif_models: A named list of motif models. Each element contains PSSM and
spatial model (6 models: "Jun_AP1", "KLF5", "JunD", "TEAD2", "MyoG", and
"Meis1")
• @additional_features: A data frame of additional features (17 features)
• @coefs: A data frame of coefficients (23 elements)
• @model_features: A matrix of the model features (logistic functions of the
motif models energies, dimensions: 14001x92)
• @normalized_energies: A matrix of normalized energies of the model features
(dimensions: 14001x6)
• @type: A vector the length of the number of peaks, indicating whether each
peak is a training ('train') or a prediction peak ('test')
• @diff_score: A numeric value representing the difference score the model was
trained on (14001 elements)
• @predicted_diff_score: A numeric value representing the predicted difference
score
• @initial_prego_models: A list of prego models used in the initial phase of
the algorithm (5 models)
• @peak_intervals: A data frame containing the peak intervals (14001 elements)
• @normalization_intervals: A data frame containing the intervals used for
energy normalization (14001 elements)
• @features_r2: A numeric vector of the added R^2 values for each feature (6
elements)
• @params: A list of parameters used for training (including:
"energy_norm_quantile", "norm_energy_max", "min_energy", "alpha", "lambda",
"peaks_size", "spat_num_bins", "spat_bin_size", "n_clust_factor",
"include_interactions", "interaction_threshold", "symmetrize_spat", "seed",
"names_map", "stats", "features_bits", "r2_threshold", and "bits_threshold")

R^2 train: 0.124
R^2 test: 0.175

→ Computing sequence features

ℹ Seed: 60427

ℹ Training on 11531 intervals (82%) and testing on 2470 intervals (18%)

ℹ Saving the train and test indices to "/net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper_raw/output/iq_3_pad_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg"

ℹ Learning prego motifs (de-novo motifs)

ℹ Extracting sequences...

ℹ Inferring 5 prego motifs...

ℹ Using 11 bins of size 40 bp

ℹ Running regression for 5 motifs



── Running first regression ──



ℹ Using 11 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Performing sampled optimization

ℹ Sampling 1 of the dataset

✔ Sampled 11530 rows from the data frame.

ℹ Sampling 0.1 of the dataset

✔ Sampled 1150 rows from the data frame.



── Generate candidate kmers

ℹ Could not find any kmer when using a threshold of 0.08. Trying with 0.04



── Regress each candidate kmer on sampled data

ℹ Running regression on 1 candidate kmers

• Bidirectional: TRUE

• Spat bin size: 40

• Number of spatial bins 11

• Length of sequence: 440

• Min gap: 0

• Max gap: 1

• Kmer length: 8

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

→ regressing with seed: "CTCCGCGG"

→ "CTCCGCGG", score (r2): 0.0630781878623553, validation score (r2): 0.0441763123893626

ℹ Performing regression on full data

ℹ Using 11 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Motif is shorter than 15, extending with wildcards

ℹ Initializing regression with the following motif: "***CTCCGCGG****"

ℹ Running regression

• Motif length: 15

• Bidirectional: TRUE

• Spat min: 30

• Spat max: 470

• Spat bin size: 40

• Number of bins: 11

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

✔ Finished running regression. Consensus: "T***CG"

✔ R^2: 0.0604

ℹ Best motif: "***CTCCGCGG****", score (r2): 0.0441763123893626



── Running regression #2 ──



ℹ Using 11 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Performing sampled optimization

ℹ Sampling 1 of the dataset

✔ Sampled 11530 rows from the data frame.

ℹ Sampling 0.1 of the dataset

✔ Sampled 1150 rows from the data frame.



── Generate candidate kmers

ℹ Could not find any kmer when using a threshold of 0.08. Trying with 0.04



── Regress each candidate kmer on sampled data

ℹ Running regression on 1 candidate kmers

• Bidirectional: TRUE

• Spat bin size: 40

• Number of spatial bins 11

• Length of sequence: 440

• Min gap: 0

• Max gap: 1

• Kmer length: 8

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

→ regressing with seed: "CTTG*TCGC"

→ "CTTG*TCGC", score (r2): 0.00110492503604101, validation score (r2): 0.00384186790663889

ℹ Performing regression on full data

ℹ Using 11 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Motif is shorter than 15, extending with wildcards

ℹ Initializing regression with the following motif: "***CTTG*TCGC***"

ℹ Running regression

• Motif length: 15

• Bidirectional: TRUE

• Spat min: 30

• Spat max: 470

• Spat bin size: 40

• Number of bins: 11

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

✔ Finished running regression. Consensus: "CTTG*TCGC"

✔ R^2: 0.0011

ℹ Best motif: "***CTTG*TCGC***", score (r2): 0.00384186790663889

ℹ R2 for models 1 and 2: 0.0613672397616056

ℹ Improvement in R2: 0.00095233795984867



── Running regression #3 ──



ℹ Using 11 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Performing sampled optimization

ℹ Sampling 1 of the dataset

✔ Sampled 11530 rows from the data frame.

ℹ Sampling 0.1 of the dataset

✔ Sampled 1150 rows from the data frame.



── Generate candidate kmers

ℹ Could not find any kmer when using a threshold of 0.08. Trying with 0.04



── Regress each candidate kmer on sampled data

ℹ Running regression on 1 candidate kmers

• Bidirectional: TRUE

• Spat bin size: 40

• Number of spatial bins 11

• Length of sequence: 440

• Min gap: 0

• Max gap: 1

• Kmer length: 8

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

→ regressing with seed: "CTTG*TCGC"

→ "CTTG*TCGC", score (r2): 0.000619182856944862, validation score (r2): 0.000258603616367314

ℹ Performing regression on full data

ℹ Using 11 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Motif is shorter than 15, extending with wildcards

ℹ Initializing regression with the following motif: "***CTTG*TCGC***"

ℹ Running regression

• Motif length: 15

• Bidirectional: TRUE

• Spat min: 30

• Spat max: 470

• Spat bin size: 40

• Number of bins: 11

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

✔ Finished running regression. Consensus: "CTTGTTCGC"

✔ R^2: 1e-04

ℹ Best motif: "***CTTG*TCGC***", score (r2): 0.000258603616367314

ℹ R2 for models 1, 2, and 3: 0.0614267803405725

ℹ Improvement in R2: 5.95405789669545e-05



── Running regression #4 ──



ℹ Using 11 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Performing sampled optimization

ℹ Sampling 1 of the dataset

✔ Sampled 11530 rows from the data frame.

ℹ Sampling 0.1 of the dataset

✔ Sampled 1150 rows from the data frame.



── Generate candidate kmers

ℹ Could not find any kmer when using a threshold of 0.08. Trying with 0.04



── Regress each candidate kmer on sampled data

ℹ Running regression on 1 candidate kmers

• Bidirectional: TRUE

• Spat bin size: 40

• Number of spatial bins 11

• Length of sequence: 440

• Min gap: 0

• Max gap: 1

• Kmer length: 8

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

→ regressing with seed: "CTTG*TCGC"

→ "CTTG*TCGC", score (r2): 0.000272842363119759, validation score (r2): 0.00214509218043627

ℹ Performing regression on full data

ℹ Using 11 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Motif is shorter than 15, extending with wildcards

ℹ Initializing regression with the following motif: "***CTTG*TCGC***"

ℹ Running regression

• Motif length: 15

• Bidirectional: TRUE

• Spat min: 30

• Spat max: 470

• Spat bin size: 40

• Number of bins: 11

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

✔ Finished running regression. Consensus: "CTTGTTCGC"

✔ R^2: 0

ℹ Best motif: "***CTTG*TCGC***", score (r2): 0.00214509218043627

ℹ R2 for models 1, 2, 3, and 4: 0.0614330934888688

ℹ Improvement in R2: 6.31314829623725e-06



── Running regression #5 ──



ℹ Using 11 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Performing sampled optimization

ℹ Sampling 1 of the dataset

✔ Sampled 11530 rows from the data frame.

ℹ Sampling 0.1 of the dataset

✔ Sampled 1150 rows from the data frame.



── Generate candidate kmers

ℹ Could not find any kmer when using a threshold of 0.08. Trying with 0.04



── Regress each candidate kmer on sampled data

ℹ Running regression on 1 candidate kmers

• Bidirectional: TRUE

• Spat bin size: 40

• Number of spatial bins 11

• Length of sequence: 440

• Min gap: 0

• Max gap: 1

• Kmer length: 8

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

→ regressing with seed: "CTTG*TCGC"

→ "CTTG*TCGC", score (r2): 0.000152088084842187, validation score (r2): 1.76143041672266e-05

ℹ Performing regression on full data

ℹ Using 11 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Motif is shorter than 15, extending with wildcards

ℹ Initializing regression with the following motif: "***CTTG*TCGC***"

ℹ Running regression

• Motif length: 15

• Bidirectional: TRUE

• Spat min: 30

• Spat max: 470

• Spat bin size: 40

• Number of bins: 11

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

✔ Finished running regression. Consensus: "CTTGYTCGC"

✔ R^2: 0

ℹ Best motif: "***CTTG*TCGC***", score (r2): 1.76143041672266e-05

ℹ R2 for models 1, 2, 3, 4, and 5: 0.061503073603732

ℹ Improvement in R2: 6.99801148631649e-05

✔ Best model: model #1 (score of 0.0604149018017569)

→ Saving the prego model to "/net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper_raw/output/iq_3_pad_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg/prego_model.rds"

→ Regressing on train set

ℹ Number of peaks: 11531

→ Extracting sequences...

ℹ Calculating correlations between 3872 motif energies and ATAC difference...

! No features with absolute correlation >= 0.2. Trying again with 0.1

ℹ Selected 640 (out of 3872) features with absolute correlation >= 0.1

ℹ Running first round of regression, # of features: 640

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
ℹ Taking 373 features with beta >= 0.01

ℹ Running second round of regression...

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
ℹ Clustering 373 features into 10 clusters...

ℹ Choosing top 10 features clusters

ℹ Features left: 373

ℹ Learning a model for each motif cluster...

ℹ Infering energies...

ℹ Running final regression, number of features: 108

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
✔ Finished running model. Number of non-zero coefficients: 107 (out of 108). R^2: 0.170542584895212

→ Matching JASPAR.mirr

→ Matched with "HOMER.TATA_box", PSSM correlation = 0.611062265408269

→ Matching HOMER.GSC

→ Matched with "HOMER.Gata4", PSSM correlation = 0.695679397919784

→ Matching HOMER.Fra1

→ Matched with "HOMER.Jun_AP1", PSSM correlation = 0.830632620028121

→ Matching JASPAR.TCF12

→ Matched with "HOMER.Klf4", PSSM correlation = 0.604851333435436

→ Matching HOCOMOCO.AP2B_HUMAN.H11MO.0.B

→ Matched with "HOMER.E2F4", PSSM correlation = 0.586716764830023

→ Matching JASPAR.KLF1

→ Matched with "HOMER.Klf4", PSSM correlation = 0.695964622605546

→ Matching JASPAR.YER184C

→ Matched with "HOMER.E2F4", PSSM correlation = 0.582727090829179

→ Matching JASPAR.CST6

→ Matched with "HOMER.JunD", PSSM correlation = 0.727047767419962

→ Matching JASPAR.ZBTB32

→ Matched with "HOMER.HIF_1a", PSSM correlation = 0.629812991884604

→ Matching JASPAR.ZNF768

→ Matched with "HOMER.GAGA_repeat", PSSM correlation = 0.627668059047814

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
ℹ Extracting sequences...

ℹ Computing motif energies for 2470 intervals and 14001 normalization intervals

ℹ Inferring the model on 2470 intervals



Number of motifs: 10

R^2 train: 0.171

R^2 test: 0.172



→ Saving the model to "/net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper_raw/output/iq_3_pad_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg/iq_regression_model.rds"

ℹ Plotting 10 motifs

ℹ Plotting motif "E2F4"

ℹ Plotting motif "TATA_box"

ℹ Plotting motif "GAGA_repeat"

ℹ Plotting motif "Gata4"

ℹ Plotting motif "Klf4.2"

ℹ Plotting motif "JunD"

ℹ Plotting motif "Klf4"

ℹ Plotting motif "HIF_1a"

ℹ Plotting motif "E2F4.2"

ℹ Plotting motif "Jun_AP1"

ℹ Saving plot...

Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
✔ Plot saved to /net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper_raw/output/iq_3_pad_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg/iq_regression_model.pdf

→ Filtering the model

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
ℹ Using 1150 samples for filtering

ℹ R^2 of the full model: 0.106541540740229

ℹ Filtering features with R^2 < 5e-04 and bits < 1.75

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by TATA_box (------TAAA-----): 0.000819678934523893. Bits: 1.85161007093604

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by Gata4 (-------GATTA---): 0.0013517902324886. Bits: 2.89914309530711

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by Jun_AP1 (---TGACTCA-----): 0.000905809429341181. Bits: 3.757996805638

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by Klf4.2 (----C-C-CCCC---): 0.00397356475781441. Bits: 4.82205568205556

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by E2F4 (---TC-GCG------): 0.00681738891593628. Bits: 2.17961049825866

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by Klf4 (-CTCCGCCCCC----): 0.00261024174461008. Bits: 8.37529821422861

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by E2F4.2 (---GGCCG-------): -0.000180388757619582. Bits: 4.56620230887945

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by JunD (---GTGAC-T-A---): -0.00300137109959618. Bits: 4.29652181275864

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by HIF_1a (-----ATAC------): -0.000647538795479602. Bits: 2.89371160675043

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by GAGA_repeat (--C-GAGA-------): -5.88428457067025e-06. Bits: 2.43048949467008

ℹ Trying to remove the following features with R^2 < 5e-04: "E2F4.2", "JunD", "HIF_1a", and "GAGA_repeat"

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ Removing "HIF_1a" changed the R^2 by -0.000243586569296059

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”

Warning message:
“glmnet.fit: algorithm did not converge”
→ Removing "E2F4.2" changed the R^2 by -0.000652878072969154

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ Not removing "GAGA_repeat" (changed the R^2 by only 0.000735603015504266).

ℹ Removed 0 features with bits < 1.75

ℹ Removed 3 features with R^2 < 5e-04

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
✔ After filtering: Number of non-zero coefficients: 95 (out of 96). R^2: 0.168204873820012. Number of models: 7

ℹ Extracting sequences...

ℹ Computing motif energies for 2470 intervals and 14001 normalization intervals

ℹ Inferring the model on 2470 intervals



Number of motifs: 7

R^2 train: 0.168

R^2 test: 0.174



→ Saving the model to "/net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper_raw/output/iq_3_pad_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg/iq_regression_filtered_model.rds"

ℹ Plotting 7 motifs

ℹ Plotting motif "E2F4"

ℹ Plotting motif "Klf4.2"

ℹ Plotting motif "Klf4"

ℹ Plotting motif "Gata4"

ℹ Plotting motif "Jun_AP1"

ℹ Plotting motif "TATA_box"

ℹ Plotting motif "GAGA_repeat"

ℹ Saving plot...

Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
✔ Plot saved to /net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper_raw/output/iq_3_pad_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg/iq_regression_filtered_model.pdf

✔ Finished IQ regression



Run `plot_traj_model_report(traj_model)` to visualize the model features

Run `plot_prediction_scatter(traj_model)` to visualize the model predictions

<TrajectoryModel> with 7 motifs and 17 additional features

Slots include:
• @model: A GLM model object. Number of non-zero coefficients: 95
• @motif_models: A named list of motif models. Each element contains PSSM and
spatial model (7 models: "TATA_box", "Gata4", "Jun_AP1", "Klf4.2", "E2F4",
"Klf4", and "GAGA_repeat")
• @additional_features: A data frame of additional features (17 features)
• @coefs: A data frame of coefficients (24 elements)
• @model_features: A matrix of the model features (logistic functions of the
motif models energies, dimensions: 14001x96)
• @normalized_energies: A matrix of normalized energies of the model features
(dimensions: 14001x7)
• @type: A vector the length of the number of peaks, indicating whether each
peak is a training ('train') or a prediction peak ('test')
• @diff_score: A numeric value representing the difference score the model was
trained on (14001 elements)
• @predicted_diff_score: A numeric value representing the predicted difference
score
• @initial_prego_models: A list of prego models used in the initial phase of
the algorithm (5 models)
• @peak_intervals: A data frame containing the peak intervals (14001 elements)
• @normalization_intervals: A data frame containing the intervals used for
energy normalization (14001 elements)
• @features_r2: A numeric vector of the added R^2 values for each feature (7
elements)
• @params: A list of parameters used for training (including:
"energy_norm_quantile", "norm_energy_max", "min_energy", "alpha", "lambda",
"peaks_size", "spat_num_bins", "spat_bin_size", "n_clust_factor",
"include_interactions", "interaction_threshold", "symmetrize_spat", "seed",
"names_map", "stats", "features_bits", "r2_threshold", and "bits_threshold")

R^2 train: 0.168
R^2 test: 0.174

In [19]:
#new
suffix <- "_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg"
run_iq_regression(
    model_type = "5",
    cgd = cgd,
    test_idxs = test_idxs,
    train_idxs = train_idxs,
    suffix = suffix
)
run_iq_regression(
    model_type = "3",
    cgd = cgd,
    test_idxs = test_idxs,
    train_idxs = train_idxs,
    suffix = suffix
)
run_iq_regression(
    model_type = "5_pad",
    cgd = cgd,
    test_idxs = test_idxs,
    train_idxs = train_idxs,
    suffix = suffix
)
run_iq_regression(
    model_type = "3_pad",
    cgd = cgd,
    test_idxs = test_idxs,
    train_idxs = train_idxs,
    suffix = suffix
)

→ Computing sequence features

ℹ Seed: 60427

ℹ Training on 11531 intervals (82%) and testing on 2470 intervals (18%)

ℹ Saving the train and test indices to "/net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper_raw/output/iq_5_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg"

ℹ Learning prego motifs (de-novo motifs)

ℹ Extracting sequences...

ℹ Inferring 5 prego motifs...

ℹ Using 15 bins of size 40 bp

ℹ Running regression for 5 motifs



── Running first regression ──



ℹ Using 15 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Performing sampled optimization

ℹ Sampling 1 of the dataset

✔ Sampled 11530 rows from the data frame.

ℹ Sampling 0.1 of the dataset

✔ Sampled 1150 rows from the data frame.



── Generate candidate kmers



── Regress each candidate kmer on sampled data

ℹ Running regression on 10 candidate kmers

• Bidirectional: TRUE

• Spat bin size: 40

• Number of spatial bins 15

• Length of sequence: 600

• Min gap: 0

• Max gap: 1

• Kmer length: 8

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

ℹ Performing regression on full data

ℹ Using 15 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Motif is shorter than 15, extending with wildcards

ℹ Initializing regression with the following motif: "***GGGGCGGG****"

ℹ Running regression

• Motif length: 15

• Bidirectional: TRUE

• Spat min: 0

• Spat max: 600

• Spat bin size: 40

• Number of bins: 15

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

✔ Finished running regression. Consensus: "CG"

✔ R^2: 0.1219

ℹ Best motif: "***GGGGCGGG****", score (r2): 0.105742518803406



── Running regression #2 ──



ℹ Using 15 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Performing sampled optimization

ℹ Sampling 1 of the dataset

✔ Sampled 11530 rows from the data frame.

ℹ Sampling 0.1 of the dataset

✔ Sampled 1150 rows from the data frame.



── Generate candidate kmers

ℹ Could not find any kmer when using a threshold of 0.08. Trying with 0.04



── Regress each candidate kmer on sampled data

ℹ Running regression on 1 candidate kmers

• Bidirectional: TRUE

• Spat bin size: 40

• Number of spatial bins 15

• Length of sequence: 600

• Min gap: 0

• Max gap: 1

• Kmer length: 8

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

→ regressing with seed: "CGCA*GCGC"

→ "CGCA*GCGC", score (r2): 0.00967030735261577, validation score (r2): 5.85775895863163e-07

ℹ Performing regression on full data

ℹ Using 15 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Motif is shorter than 15, extending with wildcards

ℹ Initializing regression with the following motif: "***CGCA*GCGC***"

ℹ Running regression

• Motif length: 15

• Bidirectional: TRUE

• Spat min: 0

• Spat max: 600

• Spat bin size: 40

• Number of bins: 15

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

✔ Finished running regression. Consensus: "RMGCA*GCGC"

✔ R^2: 0.0078

ℹ Best motif: "***CGCA*GCGC***", score (r2): 5.85775895863163e-07

ℹ R2 for models 1 and 2: 0.129527658111408

ℹ Improvement in R2: 0.00760899608932276



── Running regression #3 ──



ℹ Using 15 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Performing sampled optimization

ℹ Sampling 1 of the dataset

✔ Sampled 11530 rows from the data frame.

ℹ Sampling 0.1 of the dataset

✔ Sampled 1150 rows from the data frame.



── Generate candidate kmers

ℹ Could not find any kmer when using a threshold of 0.08. Trying with 0.04



── Regress each candidate kmer on sampled data

ℹ Running regression on 1 candidate kmers

• Bidirectional: TRUE

• Spat bin size: 40

• Number of spatial bins 15

• Length of sequence: 600

• Min gap: 0

• Max gap: 1

• Kmer length: 8

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

→ regressing with seed: "AA*ATGGCG"

→ "AA*ATGGCG", score (r2): 0.0158770407109677, validation score (r2): 0.00834522609193483

ℹ Performing regression on full data

ℹ Using 15 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Motif is shorter than 15, extending with wildcards

ℹ Initializing regression with the following motif: "***AA*ATGGCG***"

ℹ Running regression

• Motif length: 15

• Bidirectional: TRUE

• Spat min: 0

• Spat max: 600

• Spat bin size: 40

• Number of bins: 15

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

✔ Finished running regression. Consensus: "ATGG"

✔ R^2: 0.0161

ℹ Best motif: "***AA*ATGGCG***", score (r2): 0.00834522609193483

ℹ R2 for models 1, 2, and 3: 0.143267154221953

ℹ Improvement in R2: 0.0137394961105447



── Running regression #4 ──



ℹ Using 15 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Performing sampled optimization

ℹ Sampling 1 of the dataset

✔ Sampled 11530 rows from the data frame.

ℹ Sampling 0.1 of the dataset

✔ Sampled 1150 rows from the data frame.



── Generate candidate kmers

ℹ Could not find any kmer when using a threshold of 0.08. Trying with 0.04



── Regress each candidate kmer on sampled data

ℹ Running regression on 1 candidate kmers

• Bidirectional: TRUE

• Spat bin size: 40

• Number of spatial bins 15

• Length of sequence: 600

• Min gap: 0

• Max gap: 1

• Kmer length: 8

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

→ regressing with seed: "ACCAGA*CT"

→ "ACCAGA*CT", score (r2): 0.00447580469766431, validation score (r2): 0.00118388755109846

ℹ Performing regression on full data

ℹ Using 15 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Motif is shorter than 15, extending with wildcards

ℹ Initializing regression with the following motif: "***ACCAGA*CT***"

ℹ Running regression

• Motif length: 15

• Bidirectional: TRUE

• Spat min: 0

• Spat max: 600

• Spat bin size: 40

• Number of bins: 15

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

✔ Finished running regression. Consensus: "ACCA*AYCT**R"

✔ R^2: 0.0021

ℹ Best motif: "***ACCAGA*CT***", score (r2): 0.00118388755109846

ℹ R2 for models 1, 2, 3, and 4: 0.145370561262483

ℹ Improvement in R2: 0.00210340704053003



── Running regression #5 ──



ℹ Using 15 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Performing sampled optimization

ℹ Sampling 1 of the dataset

✔ Sampled 11530 rows from the data frame.

ℹ Sampling 0.1 of the dataset

✔ Sampled 1150 rows from the data frame.



── Generate candidate kmers

ℹ Could not find any kmer when using a threshold of 0.08. Trying with 0.04



── Regress each candidate kmer on sampled data

ℹ Running regression on 1 candidate kmers

• Bidirectional: TRUE

• Spat bin size: 40

• Number of spatial bins 15

• Length of sequence: 600

• Min gap: 0

• Max gap: 1

• Kmer length: 8

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

→ regressing with seed: "ACTTCCGG"

→ "ACTTCCGG", score (r2): 0.0231739295009207, validation score (r2): 0.00255263118388808

ℹ Performing regression on full data

ℹ Using 15 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Motif is shorter than 15, extending with wildcards

ℹ Initializing regression with the following motif: "***ACTTCCGG****"

ℹ Running regression

• Motif length: 15

• Bidirectional: TRUE

• Spat min: 0

• Spat max: 600

• Spat bin size: 40

• Number of bins: 15

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

✔ Finished running regression. Consensus: "CTTCC"

✔ R^2: 0.0119

ℹ Best motif: "***ACTTCCGG****", score (r2): 0.00255263118388808

ℹ R2 for models 1, 2, 3, 4, and 5: 0.155287016387279

ℹ Improvement in R2: 0.00991645512479672

✔ Best model: model #1 (score of 0.121918662022085)

→ Saving the prego model to "/net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper_raw/output/iq_5_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg/prego_model.rds"

→ Regressing on train set

ℹ Number of peaks: 11531

→ Extracting sequences...

ℹ Calculating correlations between 3872 motif energies and ATAC difference...

ℹ Selected 68 (out of 3872) features with absolute correlation >= 0.15

ℹ Running first round of regression, # of features: 68

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
ℹ Taking 53 features with beta >= 0.01

ℹ Running second round of regression...

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
ℹ Clustering 53 features into 10 clusters...

ℹ Choosing top 10 features clusters

ℹ Features left: 53

ℹ Learning a model for each motif cluster...

ℹ Infering energies...

ℹ Running final regression, number of features: 108

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
✔ Finished running model. Number of non-zero coefficients: 107 (out of 108). R^2: 0.204440983772306

→ Matching e1

→ Matched with "HOMER.Sp1", PSSM correlation = 0.660494457727532

→ Matching JOLMA.ELK1_mono_full

→ Matched with "HOMER.ETS", PSSM correlation = 0.765282685845344

→ Matching HOCOMOCO.TYY1_MOUSE.H11MO.0.A

→ Matched with "HOMER.YY1", PSSM correlation = 0.81431641879816

→ Matching JASPAR.ZBTB7A

→ Matched with "HOMER.ETS1", PSSM correlation = 0.87186923533612

→ Matching JASPAR.btd

→ Matched with "HOMER.Egr2", PSSM correlation = 0.742436294162996

→ Matching JOLMA.KLF14_mono_DBD

→ Matched with "HOMER.Klf4", PSSM correlation = 0.813670564719117

→ Matching HOCOMOCO.ATF3_HUMAN.H11MO.0.A

→ Matched with "HOMER.CRE", PSSM correlation = 0.804690579718533

→ Matching HOMER.Elk4

→ Matched with "HOMER.ETS1", PSSM correlation = 0.883651252029852

→ Matching HOCOMOCO.KLF12_HUMAN.H11MO.0.C

→ Matched with "HOMER.Sp1", PSSM correlation = 0.91547374664879

→ Matching HOCOMOCO.E2F4_MOUSE.H11MO.0.A

→ Matched with "HOMER.E2F1", PSSM correlation = 0.78318579384703

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
ℹ Extracting sequences...

ℹ Computing motif energies for 2470 intervals and 14001 normalization intervals

ℹ Inferring the model on 2470 intervals



Number of motifs: 10

R^2 train: 0.204

R^2 test: 0.21



→ Saving the model to "/net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper_raw/output/iq_5_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg/iq_regression_model.rds"

ℹ Plotting 10 motifs

Warning message:
“The `<scale>` argument of `guides()` cannot be `FALSE`. Use "none" instead as
of ggplot2 3.3.4.
ℹ The deprecated feature was likely used in the ggseqlogo package.
  Please report the issue at <https://github.com/omarwagih/ggseqlogo/issues>.”
ℹ Plotting motif "ETS1.2"

ℹ Plotting motif "Sp1"

ℹ Plotting motif "ETS"

ℹ Plotting motif "YY1"

ℹ Plotting motif "Klf4"

ℹ Plotting motif "ETS1"

ℹ Plotting motif "Sp1.2"

ℹ Plotting motif "E2F1"

ℹ Plotting motif "CRE"

ℹ Plotting motif "Egr2"

ℹ Saving plot...

Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 44 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 38 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 36 rows containing missing values or values outside the scale range
(`geom_line()`).”
✔ Plot saved to /net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper_raw/output/iq_5_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg/iq_regression_model.pdf

→ Filtering the model

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
ℹ Using 1150 samples for filtering

ℹ R^2 of the full model: 0.142737963566353

ℹ Filtering features with R^2 < 5e-04 and bits < 1.75

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by Sp1.2 (-----ACG-------): 0.010104943754276. Bits: 1.91087952029462

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by ETS (----CCGGAA-----): -8.0473600952452e-05. Bits: 4.24726680740089

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by YY1 (---A--ATGGC----): 0.01673317122472. Bits: 4.69712536512646

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by ETS1.2 (---C-GGAAGT----): -0.00508121964616043. Bits: 3.62273263669829

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by Egr2 (-GGGGGCGGA): 0.00232054936390541. Bits: 11.2589495458358

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by Klf4 (---GCCACGCCCA--): -0.00059996902167872. Bits: 7.23913932244582

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by CRE (GGTGACGTGA-): 0.00309376405016407. Bits: 9.09597700344603

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by ETS1 (---CCGGAAGT----): -0.00132776158500958. Bits: 4.92101863719443

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by Sp1 (---G-CCCGCCC---): 0.000131987301813186. Bits: 4.5484447566256

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by E2F1 (-GGGGGCGGGAA--): -0.00128893641504721. Bits: 10.3609798675915

ℹ Trying to remove the following features with R^2 < 5e-04: "ETS", "ETS1.2", "Klf4", "ETS1", "Sp1", and "E2F1"

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ Not removing "ETS1" (changed the R^2 by only 0.00226759611723709).

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ Removing "E2F1" changed the R^2 by -0.0010748367011929

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ Removing "Klf4" changed the R^2 by -0.000829354663665682

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ Not removing "ETS" (changed the R^2 by only 0.00101081116260485).

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ Not removing "Sp1" (changed the R^2 by only 0.00533190922474014).

ℹ Removed 0 features with bits < 1.75

ℹ Removed 3 features with R^2 < 5e-04

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
✔ After filtering: Number of non-zero coefficients: 96 (out of 96). R^2: 0.201072472925478. Number of models: 7

ℹ Extracting sequences...

ℹ Computing motif energies for 2470 intervals and 14001 normalization intervals

ℹ Inferring the model on 2470 intervals



Number of motifs: 7

R^2 train: 0.201

R^2 test: 0.208



→ Saving the model to "/net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper_raw/output/iq_5_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg/iq_regression_filtered_model.rds"

ℹ Plotting 7 motifs

ℹ Plotting motif "YY1"

ℹ Plotting motif "Sp1.2"

ℹ Plotting motif "CRE"

ℹ Plotting motif "Egr2"

ℹ Plotting motif "Sp1"

ℹ Plotting motif "ETS"

ℹ Plotting motif "ETS1"

ℹ Saving plot...

Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 38 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 36 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
✔ Plot saved to /net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper_raw/output/iq_5_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg/iq_regression_filtered_model.pdf

✔ Finished IQ regression



Run `plot_traj_model_report(traj_model)` to visualize the model features

Run `plot_prediction_scatter(traj_model)` to visualize the model predictions

<TrajectoryModel> with 7 motifs and 17 additional features

Slots include:
• @model: A GLM model object. Number of non-zero coefficients: 96
• @motif_models: A named list of motif models. Each element contains PSSM and
spatial model (7 models: "Sp1.2", "ETS", "YY1", "Egr2", "CRE", "ETS1", and
"Sp1")
• @additional_features: A data frame of additional features (17 features)
• @coefs: A data frame of coefficients (24 elements)
• @model_features: A matrix of the model features (logistic functions of the
motif models energies, dimensions: 14001x96)
• @normalized_energies: A matrix of normalized energies of the model features
(dimensions: 14001x7)
• @type: A vector the length of the number of peaks, indicating whether each
peak is a training ('train') or a prediction peak ('test')
• @diff_score: A numeric value representing the difference score the model was
trained on (14001 elements)
• @predicted_diff_score: A numeric value representing the predicted difference
score
• @initial_prego_models: A list of prego models used in the initial phase of
the algorithm (5 models)
• @peak_intervals: A data frame containing the peak intervals (14001 elements)
• @normalization_intervals: A data frame containing the intervals used for
energy normalization (14001 elements)
• @features_r2: A numeric vector of the added R^2 values for each feature (7
elements)
• @params: A list of parameters used for training (including:
"energy_norm_quantile", "norm_energy_max", "min_energy", "alpha", "lambda",
"peaks_size", "spat_num_bins", "spat_bin_size", "n_clust_factor",
"include_interactions", "interaction_threshold", "symmetrize_spat", "seed",
"names_map", "stats", "features_bits", "r2_threshold", and "bits_threshold")

R^2 train: 0.201
R^2 test: 0.208

→ Computing sequence features

ℹ Seed: 60427

ℹ Training on 11531 intervals (82%) and testing on 2470 intervals (18%)

ℹ Saving the train and test indices to "/net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper_raw/output/iq_3_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg"

ℹ Learning prego motifs (de-novo motifs)

ℹ Extracting sequences...

ℹ Inferring 5 prego motifs...

ℹ Using 15 bins of size 40 bp

ℹ Running regression for 5 motifs



── Running first regression ──



ℹ Using 15 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Performing sampled optimization

ℹ Sampling 1 of the dataset

✔ Sampled 11530 rows from the data frame.

ℹ Sampling 0.1 of the dataset

✔ Sampled 1150 rows from the data frame.



── Generate candidate kmers

ℹ Could not find any kmer when using a threshold of 0.08. Trying with 0.04



── Regress each candidate kmer on sampled data

ℹ Running regression on 1 candidate kmers

• Bidirectional: TRUE

• Spat bin size: 40

• Number of spatial bins 15

• Length of sequence: 600

• Min gap: 0

• Max gap: 1

• Kmer length: 8

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

→ regressing with seed: "GGGG*CGGG"

→ "GGGG*CGGG", score (r2): 0.107036274938867, validation score (r2): 0.0990299054837721

ℹ Performing regression on full data

ℹ Using 15 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Motif is shorter than 15, extending with wildcards

ℹ Initializing regression with the following motif: "***GGGG*CGGG***"

ℹ Running regression

• Motif length: 15

• Bidirectional: TRUE

• Spat min: 0

• Spat max: 600

• Spat bin size: 40

• Number of bins: 15

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

✔ Finished running regression. Consensus: "CG"

✔ R^2: 0.1066

ℹ Best motif: "***GGGG*CGGG***", score (r2): 0.0990299054837721



── Running regression #2 ──



ℹ Using 15 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Performing sampled optimization

ℹ Sampling 1 of the dataset

✔ Sampled 11530 rows from the data frame.

ℹ Sampling 0.1 of the dataset

✔ Sampled 1150 rows from the data frame.



── Generate candidate kmers

ℹ Could not find any kmer when using a threshold of 0.08. Trying with 0.04



── Regress each candidate kmer on sampled data

ℹ Running regression on 1 candidate kmers

• Bidirectional: TRUE

• Spat bin size: 40

• Number of spatial bins 15

• Length of sequence: 600

• Min gap: 0

• Max gap: 1

• Kmer length: 8

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

→ regressing with seed: "TGTA*TTAT"

→ "TGTA*TTAT", score (r2): 0.00283788528813074, validation score (r2): 0.00478780228375218

ℹ Performing regression on full data

ℹ Using 15 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Motif is shorter than 15, extending with wildcards

ℹ Initializing regression with the following motif: "***TGTA*TTAT***"

ℹ Running regression

• Motif length: 15

• Bidirectional: TRUE

• Spat min: 0

• Spat max: 600

• Spat bin size: 40

• Number of bins: 15

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

✔ Finished running regression. Consensus: "AATTAT"

✔ R^2: 0.0037

ℹ Best motif: "***TGTA*TTAT***", score (r2): 0.00478780228375218

ℹ R2 for models 1 and 2: 0.110707639864282

ℹ Improvement in R2: 0.00413677055476776



── Running regression #3 ──



ℹ Using 15 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Performing sampled optimization

ℹ Sampling 1 of the dataset

✔ Sampled 11530 rows from the data frame.

ℹ Sampling 0.1 of the dataset

✔ Sampled 1150 rows from the data frame.



── Generate candidate kmers

ℹ Could not find any kmer when using a threshold of 0.08. Trying with 0.04



── Regress each candidate kmer on sampled data

ℹ Running regression on 1 candidate kmers

• Bidirectional: TRUE

• Spat bin size: 40

• Number of spatial bins 15

• Length of sequence: 600

• Min gap: 0

• Max gap: 1

• Kmer length: 8

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

→ regressing with seed: "TCT*GAACC"

→ "TCT*GAACC", score (r2): 0.00291940085305425, validation score (r2): 0.00160970375223141

ℹ Performing regression on full data

ℹ Using 15 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Motif is shorter than 15, extending with wildcards

ℹ Initializing regression with the following motif: "***TCT*GAACC***"

ℹ Running regression

• Motif length: 15

• Bidirectional: TRUE

• Spat min: 0

• Spat max: 600

• Spat bin size: 40

• Number of bins: 15

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

✔ Finished running regression. Consensus: "TCT*GAACC"

✔ R^2: 0.0012

ℹ Best motif: "***TCT*GAACC***", score (r2): 0.00160970375223141

ℹ R2 for models 1, 2, and 3: 0.111876861255564

ℹ Improvement in R2: 0.001169221391282



── Running regression #4 ──



ℹ Using 15 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Performing sampled optimization

ℹ Sampling 1 of the dataset

✔ Sampled 11530 rows from the data frame.

ℹ Sampling 0.1 of the dataset

✔ Sampled 1150 rows from the data frame.



── Generate candidate kmers

ℹ Could not find any kmer when using a threshold of 0.08. Trying with 0.04



── Regress each candidate kmer on sampled data

ℹ Running regression on 1 candidate kmers

• Bidirectional: TRUE

• Spat bin size: 40

• Number of spatial bins 15

• Length of sequence: 600

• Min gap: 0

• Max gap: 1

• Kmer length: 8

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

→ regressing with seed: "GCGCATGC"

→ "GCGCATGC", score (r2): 0.000462674672611587, validation score (r2): 0.000406775466097393

ℹ Performing regression on full data

ℹ Using 15 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Motif is shorter than 15, extending with wildcards

ℹ Initializing regression with the following motif: "***GCGCATGC****"

ℹ Running regression

• Motif length: 15

• Bidirectional: TRUE

• Spat min: 0

• Spat max: 600

• Spat bin size: 40

• Number of bins: 15

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

✔ Finished running regression. Consensus: "GCGCATGC"

✔ R^2: 2e-04

ℹ Best motif: "***GCGCATGC****", score (r2): 0.000406775466097393

ℹ R2 for models 1, 2, 3, and 4: 0.112181908522617

ℹ Improvement in R2: 0.000305047267052411



── Running regression #5 ──



ℹ Using 15 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Performing sampled optimization

ℹ Sampling 1 of the dataset

✔ Sampled 11530 rows from the data frame.

ℹ Sampling 0.1 of the dataset

✔ Sampled 1150 rows from the data frame.



── Generate candidate kmers

ℹ Could not find any kmer when using a threshold of 0.08. Trying with 0.04



── Regress each candidate kmer on sampled data

ℹ Running regression on 1 candidate kmers

• Bidirectional: TRUE

• Spat bin size: 40

• Number of spatial bins 15

• Length of sequence: 600

• Min gap: 0

• Max gap: 1

• Kmer length: 8

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

→ regressing with seed: "TCT*GAACC"

→ "TCT*GAACC", score (r2): 0.00208969531299547, validation score (r2): 0.00197500452485957

ℹ Performing regression on full data

ℹ Using 15 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Motif is shorter than 15, extending with wildcards

ℹ Initializing regression with the following motif: "***TCT*GAACC***"

ℹ Running regression

• Motif length: 15

• Bidirectional: TRUE

• Spat min: 0

• Spat max: 600

• Spat bin size: 40

• Number of bins: 15

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

✔ Finished running regression. Consensus: "WTCT**AACC"

✔ R^2: 5e-04

ℹ Best motif: "***TCT*GAACC***", score (r2): 0.00197500452485957

ℹ R2 for models 1, 2, 3, 4, and 5: 0.112673257659356

ℹ Improvement in R2: 0.000491349136739275

✔ Best model: model #1 (score of 0.106570869309514)

→ Saving the prego model to "/net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper_raw/output/iq_3_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg/prego_model.rds"

→ Regressing on train set

ℹ Number of peaks: 11531

→ Extracting sequences...

ℹ Calculating correlations between 3872 motif energies and ATAC difference...

! No features with absolute correlation >= 0.15. Trying again with 0.075

ℹ Selected 700 (out of 3872) features with absolute correlation >= 0.075

ℹ Running first round of regression, # of features: 700

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
ℹ Taking 466 features with beta >= 0.01

ℹ Running second round of regression...

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
ℹ Clustering 465 features into 10 clusters...

ℹ Choosing top 10 features clusters

ℹ Features left: 465

ℹ Learning a model for each motif cluster...

ℹ Infering energies...

ℹ Running final regression, number of features: 108

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
✔ Finished running model. Number of non-zero coefficients: 108 (out of 108). R^2: 0.265002347603524

→ Matching JOLMA.FEV_mono_DBD

→ Matched with "HOMER.GABPA", PSSM correlation = 0.893746775857918

→ Matching HOCOMOCO.THAP1_HUMAN.H11MO.0.C

→ Matched with "HOMER.Sp1", PSSM correlation = 0.530277985820149

→ Matching JOLMA.ESX1_mono_full

→ Matched with "HOMER.Lhx2", PSSM correlation = 0.666015882475656

→ Matching JASPAR.DAL82

→ Matched with "HOMER.NRF1", PSSM correlation = 0.832351352701554

→ Matching HOCOMOCO.SMAD2_MOUSE.H11MO.0.A

→ Matched with "HOMER.NF1_halfsite", PSSM correlation = 0.76640636920236

→ Matching HOCOMOCO.KLF1_HUMAN.H11MO.0.A

→ Matched with "HOMER.KLF5", PSSM correlation = 0.800590885929077

→ Matching JOLMA.YY1_mono_full

→ Matched with "HOMER.YY1", PSSM correlation = 0.902098360145579

→ Matching JASPAR.Atf1

→ Matched with "HOMER.Atf1", PSSM correlation = 0.691495849534117

→ Matching HOMER.bZIPIRF

→ Matched with "HOMER.GATA3_2", PSSM correlation = 0.849990845028042

→ Matching e5

→ Matched with "HOMER.Pit1", PSSM correlation = 0.505750431221846

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
ℹ Extracting sequences...

ℹ Computing motif energies for 2470 intervals and 14001 normalization intervals

ℹ Inferring the model on 2470 intervals



Number of motifs: 10

R^2 train: 0.265

R^2 test: 0.258



→ Saving the model to "/net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper_raw/output/iq_3_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg/iq_regression_model.rds"

ℹ Plotting 10 motifs

ℹ Plotting motif "Pit1"

ℹ Plotting motif "GABPA"

ℹ Plotting motif "YY1"

ℹ Plotting motif "KLF5"

ℹ Plotting motif "Sp1"

ℹ Plotting motif "Lhx2"

ℹ Plotting motif "NRF1"

ℹ Plotting motif "GATA3_2"

ℹ Plotting motif "NF1_halfsite"

ℹ Plotting motif "Atf1"

ℹ Saving plot...

Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
✔ Plot saved to /net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper_raw/output/iq_3_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg/iq_regression_model.pdf

→ Filtering the model

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
ℹ Using 1150 samples for filtering

ℹ R^2 of the full model: 0.206022000807689

ℹ Filtering features with R^2 < 5e-04 and bits < 1.75

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by GABPA (--CCGGAAG------): 0.00895984997760421. Bits: 4.23841650349289

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by Sp1 (-----CG--------): 0.00875678953082071. Bits: 2.11566522791985

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by Lhx2 (------TAAAT----): 0.0158253185634674. Bits: 3.97857073885636

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by NRF1 (--GCGCA-GCGC---): 0.00283062850333443. Bits: 11.3812440276032

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by NF1_halfsite (-------GCCAA---): 0.00135117176420288. Bits: 4.96952263386465

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by KLF5 (-G-GGGCGGA-C---): 0.00755315076676871. Bits: 8.94662810717021

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by YY1 (------ATGGC-G--): 0.0106379389362447. Bits: 4.43713191476873

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by Atf1 (---GTCACG------): 0.000185683705102996. Bits: 3.35587068161671

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by GATA3_2 (---AGATAA------): -0.000396551564513764. Bits: 3.49678452743172

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by Pit1 (---GGTTC-AGAA--): 0.00953227706390697. Bits: 8.64151117355903

ℹ Trying to remove the following features with R^2 < 5e-04: "Atf1" and "GATA3_2"

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ Not removing "Atf1" (changed the R^2 by only 0.00121710021800658).

ℹ Removed 0 features with bits < 1.75

ℹ Removed 1 features with R^2 < 5e-04

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
✔ After filtering: Number of non-zero coefficients: 103 (out of 104). R^2: 0.261088595215155. Number of models: 9

ℹ Extracting sequences...

ℹ Computing motif energies for 2470 intervals and 14001 normalization intervals

ℹ Inferring the model on 2470 intervals



Number of motifs: 9

R^2 train: 0.261

R^2 test: 0.256



→ Saving the model to "/net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper_raw/output/iq_3_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg/iq_regression_filtered_model.rds"

ℹ Plotting 9 motifs

ℹ Plotting motif "Lhx2"

ℹ Plotting motif "YY1"

ℹ Plotting motif "Pit1"

ℹ Plotting motif "GABPA"

ℹ Plotting motif "Sp1"

ℹ Plotting motif "KLF5"

ℹ Plotting motif "NRF1"

ℹ Plotting motif "NF1_halfsite"

ℹ Plotting motif "Atf1"

ℹ Saving plot...

Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”

Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
✔ Plot saved to /net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper_raw/output/iq_3_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg/iq_regression_filtered_model.pdf

✔ Finished IQ regression



Run `plot_traj_model_report(traj_model)` to visualize the model features

Run `plot_prediction_scatter(traj_model)` to visualize the model predictions

<TrajectoryModel> with 9 motifs and 17 additional features

Slots include:
• @model: A GLM model object. Number of non-zero coefficients: 103
• @motif_models: A named list of motif models. Each element contains PSSM and
spatial model (9 models: "GABPA", "Sp1", "Lhx2", "NRF1", "NF1_halfsite",
"KLF5", "YY1", "Atf1", and "Pit1")
• @additional_features: A data frame of additional features (17 features)
• @coefs: A data frame of coefficients (26 elements)
• @model_features: A matrix of the model features (logistic functions of the
motif models energies, dimensions: 14001x104)
• @normalized_energies: A matrix of normalized energies of the model features
(dimensions: 14001x9)
• @type: A vector the length of the number of peaks, indicating whether each
peak is a training ('train') or a prediction peak ('test')
• @diff_score: A numeric value representing the difference score the model was
trained on (14001 elements)
• @predicted_diff_score: A numeric value representing the predicted difference
score
• @initial_prego_models: A list of prego models used in the initial phase of
the algorithm (5 models)
• @peak_intervals: A data frame containing the peak intervals (14001 elements)
• @normalization_intervals: A data frame containing the intervals used for
energy normalization (14001 elements)
• @features_r2: A numeric vector of the added R^2 values for each feature (9
elements)
• @params: A list of parameters used for training (including:
"energy_norm_quantile", "norm_energy_max", "min_energy", "alpha", "lambda",
"peaks_size", "spat_num_bins", "spat_bin_size", "n_clust_factor",
"include_interactions", "interaction_threshold", "symmetrize_spat", "seed",
"names_map", "stats", "features_bits", "r2_threshold", and "bits_threshold")

R^2 train: 0.261
R^2 test: 0.256

→ Computing sequence features

ℹ Seed: 60427

ℹ Training on 11531 intervals (82%) and testing on 2470 intervals (18%)

ℹ Saving the train and test indices to "/net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper_raw/output/iq_5_pad_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg"

ℹ Learning prego motifs (de-novo motifs)

ℹ Extracting sequences...

ℹ Inferring 5 prego motifs...

ℹ Using 11 bins of size 40 bp

ℹ Running regression for 5 motifs



── Running first regression ──



ℹ Using 11 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Performing sampled optimization

ℹ Sampling 1 of the dataset

✔ Sampled 11530 rows from the data frame.

ℹ Sampling 0.1 of the dataset

✔ Sampled 1150 rows from the data frame.



── Generate candidate kmers



── Regress each candidate kmer on sampled data

ℹ Running regression on 10 candidate kmers

• Bidirectional: TRUE

• Spat bin size: 40

• Number of spatial bins 11

• Length of sequence: 440

• Min gap: 0

• Max gap: 1

• Kmer length: 8

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

ℹ Performing regression on full data

ℹ Using 11 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Motif is shorter than 15, extending with wildcards

ℹ Initializing regression with the following motif: "***TGGGA*TAC***"

ℹ Running regression

• Motif length: 15

• Bidirectional: TRUE

• Spat min: 30

• Spat max: 470

• Spat bin size: 40

• Number of bins: 11

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

✔ Finished running regression. Consensus: NA

✔ R^2: 0.087

ℹ Best motif: "***TGGGA*TAC***", score (r2): 0.0609615259368801



── Running regression #2 ──



ℹ Using 11 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Performing sampled optimization

ℹ Sampling 1 of the dataset

✔ Sampled 11530 rows from the data frame.

ℹ Sampling 0.1 of the dataset

✔ Sampled 1150 rows from the data frame.



── Generate candidate kmers

ℹ Could not find any kmer when using a threshold of 0.08. Trying with 0.04



── Regress each candidate kmer on sampled data

ℹ Running regression on 1 candidate kmers

• Bidirectional: TRUE

• Spat bin size: 40

• Number of spatial bins 11

• Length of sequence: 440

• Min gap: 0

• Max gap: 1

• Kmer length: 8

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

→ regressing with seed: "GCTCTGCG"

→ "GCTCTGCG", score (r2): 0.0031262635809493, validation score (r2): 0.00010495290301675

ℹ Performing regression on full data

ℹ Using 11 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Motif is shorter than 15, extending with wildcards

ℹ Initializing regression with the following motif: "***GCTCTGCG****"

ℹ Running regression

• Motif length: 15

• Bidirectional: TRUE

• Spat min: 30

• Spat max: 470

• Spat bin size: 40

• Number of bins: 11

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

✔ Finished running regression. Consensus: "G*TCTGCG"

✔ R^2: 0.003

ℹ Best motif: "***GCTCTGCG****", score (r2): 0.00010495290301675

ℹ R2 for models 1 and 2: 0.0907566136790459

ℹ Improvement in R2: 0.00373889903006895



── Running regression #3 ──



ℹ Using 11 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Performing sampled optimization

ℹ Sampling 1 of the dataset

✔ Sampled 11530 rows from the data frame.

ℹ Sampling 0.1 of the dataset

✔ Sampled 1150 rows from the data frame.



── Generate candidate kmers

ℹ Could not find any kmer when using a threshold of 0.08. Trying with 0.04



── Regress each candidate kmer on sampled data

ℹ Running regression on 1 candidate kmers

• Bidirectional: TRUE

• Spat bin size: 40

• Number of spatial bins 11

• Length of sequence: 440

• Min gap: 0

• Max gap: 1

• Kmer length: 8

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

→ regressing with seed: "AAT*ACCCC"

→ "AAT*ACCCC", score (r2): 0.00531786064823402, validation score (r2): 0.00115193897782444

ℹ Performing regression on full data

ℹ Using 11 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Motif is shorter than 15, extending with wildcards

ℹ Initializing regression with the following motif: "***AAT*ACCCC***"

ℹ Running regression

• Motif length: 15

• Bidirectional: TRUE

• Spat min: 30

• Spat max: 470

• Spat bin size: 40

• Number of bins: 11

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

✔ Finished running regression. Consensus: "AAT*ACC*C"

✔ R^2: 0.006

ℹ Best motif: "***AAT*ACCCC***", score (r2): 0.00115193897782444

ℹ R2 for models 1, 2, and 3: 0.0958341326627047

ℹ Improvement in R2: 0.00507751898365881



── Running regression #4 ──



ℹ Using 11 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Performing sampled optimization

ℹ Sampling 1 of the dataset

✔ Sampled 11530 rows from the data frame.

ℹ Sampling 0.1 of the dataset

✔ Sampled 1150 rows from the data frame.



── Generate candidate kmers

ℹ Could not find any kmer when using a threshold of 0.08. Trying with 0.04



── Regress each candidate kmer on sampled data

ℹ Running regression on 1 candidate kmers

• Bidirectional: TRUE

• Spat bin size: 40

• Number of spatial bins 11

• Length of sequence: 440

• Min gap: 0

• Max gap: 1

• Kmer length: 8

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

→ regressing with seed: "GGAGGT*CC"

→ "GGAGGT*CC", score (r2): 0.000701745416447023, validation score (r2): 4.57880386195667e-05

ℹ Performing regression on full data

ℹ Using 11 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Motif is shorter than 15, extending with wildcards

ℹ Initializing regression with the following motif: "***GGAGGT*CC***"

ℹ Running regression

• Motif length: 15

• Bidirectional: TRUE

• Spat min: 30

• Spat max: 470

• Spat bin size: 40

• Number of bins: 11

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

✔ Finished running regression. Consensus: "GGAGGT*CC"

✔ R^2: 5e-04

ℹ Best motif: "***GGAGGT*CC***", score (r2): 4.57880386195667e-05

ℹ R2 for models 1, 2, 3, and 4: 0.0967399408240368

ℹ Improvement in R2: 0.000905808161332164



── Running regression #5 ──



ℹ Using 11 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Performing sampled optimization

ℹ Sampling 1 of the dataset

✔ Sampled 11530 rows from the data frame.

ℹ Sampling 0.1 of the dataset

✔ Sampled 1150 rows from the data frame.



── Generate candidate kmers

ℹ Could not find any kmer when using a threshold of 0.08. Trying with 0.04



── Regress each candidate kmer on sampled data

ℹ Running regression on 1 candidate kmers

• Bidirectional: TRUE

• Spat bin size: 40

• Number of spatial bins 11

• Length of sequence: 440

• Min gap: 0

• Max gap: 1

• Kmer length: 8

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

→ regressing with seed: "GCGACTGT"

→ "GCGACTGT", score (r2): 0.000804888658348, validation score (r2): 1.03735206601705e-06

ℹ Performing regression on full data

ℹ Using 11 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Motif is shorter than 15, extending with wildcards

ℹ Initializing regression with the following motif: "***GCGACTGT****"

ℹ Running regression

• Motif length: 15

• Bidirectional: TRUE

• Spat min: 30

• Spat max: 470

• Spat bin size: 40

• Number of bins: 11

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

✔ Finished running regression. Consensus: "GCGACTGT**R"

✔ R^2: 8e-04

ℹ Best motif: "***GCGACTGT****", score (r2): 1.03735206601705e-06

ℹ R2 for models 1, 2, 3, 4, and 5: 0.0974703506648914

ℹ Improvement in R2: 0.00073040984085454

✔ Best model: model #1 (score of 0.0870177146489769)

→ Saving the prego model to "/net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper_raw/output/iq_5_pad_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg/prego_model.rds"

→ Regressing on train set

ℹ Number of peaks: 11531

→ Extracting sequences...

ℹ Calculating correlations between 3872 motif energies and ATAC difference...

! No features with absolute correlation >= 0.2. Trying again with 0.1

ℹ Selected 1346 (out of 3872) features with absolute correlation >= 0.1

ℹ Running first round of regression, # of features: 1346

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
ℹ Taking 831 features with beta >= 0.01

ℹ Running second round of regression...

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
ℹ Clustering 828 features into 10 clusters...

ℹ Choosing top 10 features clusters

ℹ Features left: 828

ℹ Learning a model for each motif cluster...

ℹ Infering energies...

ℹ Running final regression, number of features: 108

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
✔ Finished running model. Number of non-zero coefficients: 108 (out of 108). R^2: 0.137726791073488

→ Matching JOLMA.HOXB13_mono_DBD_1

→ Matched with "HOMER.GSC", PSSM correlation = 0.570956987547146

→ Matching JASPAR.FOSL1::JUND.MA1142.1

→ Matched with "HOMER.Jun_AP1", PSSM correlation = 0.815354462760487

→ Matching HOCOMOCO.KLF3_MOUSE.H11MO.0.A

→ Matched with "HOMER.KLF5", PSSM correlation = 0.882751089828118

→ Matching JOLMA.DPRX_mono_DBD_1

→ Matched with "HOMER.GSC", PSSM correlation = 0.641717386086804

→ Matching HOCOMOCO.ZIC2_MOUSE.H11MO.0.C

→ Matched with "HOMER.ETS1", PSSM correlation = 0.557760576267912

→ Matching HOMER.Atf1

→ Matched with "HOMER.JunD", PSSM correlation = 0.863181946933636

→ Matching JASPAR.ARF39

→ Matched with "HOMER.Klf4", PSSM correlation = 0.552868202937128

→ Matching JASPAR.MEF2D

→ Matched with "HOMER.TEAD2", PSSM correlation = 0.711868958325568

→ Matching JASPAR.SREBF2.MA0828.2

→ Matched with "HOMER.MyoG", PSSM correlation = 0.501745935485428

→ Matching JASPAR.ZNF574

→ Matched with "HOMER.Meis1", PSSM correlation = 0.590852961934174

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
ℹ Extracting sequences...

ℹ Computing motif energies for 2470 intervals and 14001 normalization intervals

ℹ Inferring the model on 2470 intervals



Number of motifs: 10

R^2 train: 0.138

R^2 test: 0.18



→ Saving the model to "/net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper_raw/output/iq_5_pad_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg/iq_regression_model.rds"

ℹ Plotting 10 motifs

ℹ Plotting motif "Meis1"

ℹ Plotting motif "MyoG"

ℹ Plotting motif "Jun_AP1"

ℹ Plotting motif "Klf4"

ℹ Plotting motif "GSC"

ℹ Plotting motif "KLF5"

ℹ Plotting motif "GSC.2"

ℹ Plotting motif "JunD"

ℹ Plotting motif "TEAD2"

ℹ Plotting motif "ETS1"

ℹ Saving plot...

Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
✔ Plot saved to /net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper_raw/output/iq_5_pad_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg/iq_regression_model.pdf

→ Filtering the model

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
ℹ Using 1150 samples for filtering

ℹ R^2 of the full model: 0.0751987778163116

ℹ Filtering features with R^2 < 5e-04 and bits < 1.75

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by GSC.2 (-----T-A-------): 0.00100261746751974. Bits: 1.01434602523677

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by Jun_AP1 (---TGACTCA-----): 0.000613926641782947. Bits: 3.59549146122894

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by KLF5 (----GGGCG------): 0.00133340334779473. Bits: 4.66686097332569

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by GSC (-----GGGATTA---): -0.00141910864159391. Bits: 4.47255242712528

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by ETS1 (---GGAGGT-CC---): -0.000451958977188485. Bits: 2.73623909886248

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by JunD (--G-TGACGT-A---): 0.000471079437178668. Bits: 3.88172230410846

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by Klf4 (---CCCC-C------): -0.00112144001239957. Bits: 3.11156762179441

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by TEAD2 (-----AG-AAT----): 0.000500158073030305. Bits: 2.66614120947567

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
→ R^2 added by MyoG (-GCC-AGGC-A-A-A): 0.00784298960445828. Bits: 4.14527640537453

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by Meis1 (----CAGA-A-----): 0.00165124180742753. Bits: 2.15643447352518

ℹ Removing the following features with bits < 1.75: "GSC.2"

ℹ Trying to remove the following features with R^2 < 5e-04: "GSC", "ETS1", "JunD", and "Klf4"

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ Removing "Klf4" changed the R^2 by -0.000746891137783673

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ Removing "ETS1" changed the R^2 by -1.65498571228079e-05

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ Not removing "JunD" (changed the R^2 by only 0.00136408578755071).

ℹ Removed 1 features with bits < 1.75

ℹ Removed 3 features with R^2 < 5e-04

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
✔ After filtering: Number of non-zero coefficients: 92 (out of 92). R^2: 0.124323993969668. Number of models: 6

ℹ Extracting sequences...

ℹ Computing motif energies for 2470 intervals and 14001 normalization intervals

ℹ Inferring the model on 2470 intervals



Number of motifs: 6

R^2 train: 0.124

R^2 test: 0.175



→ Saving the model to "/net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper_raw/output/iq_5_pad_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg/iq_regression_filtered_model.rds"

ℹ Plotting 6 motifs

ℹ Plotting motif "MyoG"

ℹ Plotting motif "Meis1"

ℹ Plotting motif "KLF5"

ℹ Plotting motif "Jun_AP1"

ℹ Plotting motif "TEAD2"

ℹ Plotting motif "JunD"

ℹ Saving plot...

Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
✔ Plot saved to /net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper_raw/output/iq_5_pad_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg/iq_regression_filtered_model.pdf

✔ Finished IQ regression



Run `plot_traj_model_report(traj_model)` to visualize the model features

Run `plot_prediction_scatter(traj_model)` to visualize the model predictions

<TrajectoryModel> with 6 motifs and 17 additional features

Slots include:
• @model: A GLM model object. Number of non-zero coefficients: 92
• @motif_models: A named list of motif models. Each element contains PSSM and
spatial model (6 models: "Jun_AP1", "KLF5", "JunD", "TEAD2", "MyoG", and
"Meis1")
• @additional_features: A data frame of additional features (17 features)
• @coefs: A data frame of coefficients (23 elements)
• @model_features: A matrix of the model features (logistic functions of the
motif models energies, dimensions: 14001x92)
• @normalized_energies: A matrix of normalized energies of the model features
(dimensions: 14001x6)
• @type: A vector the length of the number of peaks, indicating whether each
peak is a training ('train') or a prediction peak ('test')
• @diff_score: A numeric value representing the difference score the model was
trained on (14001 elements)
• @predicted_diff_score: A numeric value representing the predicted difference
score
• @initial_prego_models: A list of prego models used in the initial phase of
the algorithm (5 models)
• @peak_intervals: A data frame containing the peak intervals (14001 elements)
• @normalization_intervals: A data frame containing the intervals used for
energy normalization (14001 elements)
• @features_r2: A numeric vector of the added R^2 values for each feature (6
elements)
• @params: A list of parameters used for training (including:
"energy_norm_quantile", "norm_energy_max", "min_energy", "alpha", "lambda",
"peaks_size", "spat_num_bins", "spat_bin_size", "n_clust_factor",
"include_interactions", "interaction_threshold", "symmetrize_spat", "seed",
"names_map", "stats", "features_bits", "r2_threshold", and "bits_threshold")

R^2 train: 0.124
R^2 test: 0.175

→ Computing sequence features

ℹ Seed: 60427

ℹ Training on 11531 intervals (82%) and testing on 2470 intervals (18%)

ℹ Saving the train and test indices to "/net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper_raw/output/iq_3_pad_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg"

ℹ Learning prego motifs (de-novo motifs)

ℹ Extracting sequences...

ℹ Inferring 5 prego motifs...

ℹ Using 11 bins of size 40 bp

ℹ Running regression for 5 motifs



── Running first regression ──



ℹ Using 11 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Performing sampled optimization

ℹ Sampling 1 of the dataset

✔ Sampled 11530 rows from the data frame.

ℹ Sampling 0.1 of the dataset

✔ Sampled 1150 rows from the data frame.



── Generate candidate kmers

ℹ Could not find any kmer when using a threshold of 0.08. Trying with 0.04



── Regress each candidate kmer on sampled data

ℹ Running regression on 1 candidate kmers

• Bidirectional: TRUE

• Spat bin size: 40

• Number of spatial bins 11

• Length of sequence: 440

• Min gap: 0

• Max gap: 1

• Kmer length: 8

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

→ regressing with seed: "CTCCGCGG"

→ "CTCCGCGG", score (r2): 0.0630781878623511, validation score (r2): 0.0441763123893626

ℹ Performing regression on full data

ℹ Using 11 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Motif is shorter than 15, extending with wildcards

ℹ Initializing regression with the following motif: "***CTCCGCGG****"

ℹ Running regression

• Motif length: 15

• Bidirectional: TRUE

• Spat min: 30

• Spat max: 470

• Spat bin size: 40

• Number of bins: 11

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

✔ Finished running regression. Consensus: "T***CG"

✔ R^2: 0.0604

ℹ Best motif: "***CTCCGCGG****", score (r2): 0.0441763123893626



── Running regression #2 ──



ℹ Using 11 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Performing sampled optimization

ℹ Sampling 1 of the dataset

✔ Sampled 11530 rows from the data frame.

ℹ Sampling 0.1 of the dataset

✔ Sampled 1150 rows from the data frame.



── Generate candidate kmers

ℹ Could not find any kmer when using a threshold of 0.08. Trying with 0.04



── Regress each candidate kmer on sampled data

ℹ Running regression on 1 candidate kmers

• Bidirectional: TRUE

• Spat bin size: 40

• Number of spatial bins 11

• Length of sequence: 440

• Min gap: 0

• Max gap: 1

• Kmer length: 8

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

→ regressing with seed: "CTTG*TCGC"

→ "CTTG*TCGC", score (r2): 0.00110492503604097, validation score (r2): 0.00384186790663889

ℹ Performing regression on full data

ℹ Using 11 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Motif is shorter than 15, extending with wildcards

ℹ Initializing regression with the following motif: "***CTTG*TCGC***"

ℹ Running regression

• Motif length: 15

• Bidirectional: TRUE

• Spat min: 30

• Spat max: 470

• Spat bin size: 40

• Number of bins: 11

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

✔ Finished running regression. Consensus: "CTTG*TCGC"

✔ R^2: 0.0011

ℹ Best motif: "***CTTG*TCGC***", score (r2): 0.00384186790663889

ℹ R2 for models 1 and 2: 0.0613672397616056

ℹ Improvement in R2: 0.000952337959848545



── Running regression #3 ──



ℹ Using 11 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Performing sampled optimization

ℹ Sampling 1 of the dataset

✔ Sampled 11530 rows from the data frame.

ℹ Sampling 0.1 of the dataset

✔ Sampled 1150 rows from the data frame.



── Generate candidate kmers

ℹ Could not find any kmer when using a threshold of 0.08. Trying with 0.04



── Regress each candidate kmer on sampled data

ℹ Running regression on 1 candidate kmers

• Bidirectional: TRUE

• Spat bin size: 40

• Number of spatial bins 11

• Length of sequence: 440

• Min gap: 0

• Max gap: 1

• Kmer length: 8

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

→ regressing with seed: "CTTG*TCGC"

→ "CTTG*TCGC", score (r2): 0.000619182856944862, validation score (r2): 0.000258603616367315

ℹ Performing regression on full data

ℹ Using 11 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Motif is shorter than 15, extending with wildcards

ℹ Initializing regression with the following motif: "***CTTG*TCGC***"

ℹ Running regression

• Motif length: 15

• Bidirectional: TRUE

• Spat min: 30

• Spat max: 470

• Spat bin size: 40

• Number of bins: 11

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

✔ Finished running regression. Consensus: "CTTGTTCGC"

✔ R^2: 1e-04

ℹ Best motif: "***CTTG*TCGC***", score (r2): 0.000258603616367315

ℹ R2 for models 1, 2, and 3: 0.0614267803405725

ℹ Improvement in R2: 5.95405789669545e-05



── Running regression #4 ──



ℹ Using 11 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Performing sampled optimization

ℹ Sampling 1 of the dataset

✔ Sampled 11530 rows from the data frame.

ℹ Sampling 0.1 of the dataset

✔ Sampled 1150 rows from the data frame.



── Generate candidate kmers

ℹ Could not find any kmer when using a threshold of 0.08. Trying with 0.04



── Regress each candidate kmer on sampled data

ℹ Running regression on 1 candidate kmers

• Bidirectional: TRUE

• Spat bin size: 40

• Number of spatial bins 11

• Length of sequence: 440

• Min gap: 0

• Max gap: 1

• Kmer length: 8

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

→ regressing with seed: "CTTG*TCGC"

→ "CTTG*TCGC", score (r2): 0.000272842363119784, validation score (r2): 0.00214509218043626

ℹ Performing regression on full data

ℹ Using 11 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Motif is shorter than 15, extending with wildcards

ℹ Initializing regression with the following motif: "***CTTG*TCGC***"

ℹ Running regression

• Motif length: 15

• Bidirectional: TRUE

• Spat min: 30

• Spat max: 470

• Spat bin size: 40

• Number of bins: 11

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

✔ Finished running regression. Consensus: "CTTGTTCGC"

✔ R^2: 0

ℹ Best motif: "***CTTG*TCGC***", score (r2): 0.00214509218043626

ℹ R2 for models 1, 2, 3, and 4: 0.0614330934888688

ℹ Improvement in R2: 6.31314829623725e-06



── Running regression #5 ──



ℹ Using 11 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Performing sampled optimization

ℹ Sampling 1 of the dataset

✔ Sampled 11530 rows from the data frame.

ℹ Sampling 0.1 of the dataset

✔ Sampled 1150 rows from the data frame.



── Generate candidate kmers

ℹ Could not find any kmer when using a threshold of 0.08. Trying with 0.04



── Regress each candidate kmer on sampled data

ℹ Running regression on 1 candidate kmers

• Bidirectional: TRUE

• Spat bin size: 40

• Number of spatial bins 11

• Length of sequence: 440

• Min gap: 0

• Max gap: 1

• Kmer length: 8

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

→ regressing with seed: "CTTG*TCGC"

→ "CTTG*TCGC", score (r2): 0.000152088084842185, validation score (r2): 1.76143041672264e-05

ℹ Performing regression on full data

ℹ Using 11 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Motif is shorter than 15, extending with wildcards

ℹ Initializing regression with the following motif: "***CTTG*TCGC***"

ℹ Running regression

• Motif length: 15

• Bidirectional: TRUE

• Spat min: 30

• Spat max: 470

• Spat bin size: 40

• Number of bins: 11

• Improve epsilon: 1e-04

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

✔ Finished running regression. Consensus: "CTTGYTCGC"

✔ R^2: 0

ℹ Best motif: "***CTTG*TCGC***", score (r2): 1.76143041672264e-05

ℹ R2 for models 1, 2, 3, 4, and 5: 0.061503073603732

ℹ Improvement in R2: 6.99801148631649e-05

✔ Best model: model #1 (score of 0.060414901801757)

→ Saving the prego model to "/net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper_raw/output/iq_3_pad_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg/prego_model.rds"

→ Regressing on train set

ℹ Number of peaks: 11531

→ Extracting sequences...

ℹ Calculating correlations between 3872 motif energies and ATAC difference...

! No features with absolute correlation >= 0.2. Trying again with 0.1

ℹ Selected 640 (out of 3872) features with absolute correlation >= 0.1

ℹ Running first round of regression, # of features: 640

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
ℹ Taking 373 features with beta >= 0.01

ℹ Running second round of regression...

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
ℹ Clustering 373 features into 10 clusters...

ℹ Choosing top 10 features clusters

ℹ Features left: 373

ℹ Learning a model for each motif cluster...

ℹ Infering energies...

ℹ Running final regression, number of features: 108

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
✔ Finished running model. Number of non-zero coefficients: 107 (out of 108). R^2: 0.170542584895212

→ Matching JASPAR.mirr

→ Matched with "HOMER.TATA_box", PSSM correlation = 0.611062265408269

→ Matching HOMER.GSC

→ Matched with "HOMER.Gata4", PSSM correlation = 0.695679397919784

→ Matching HOMER.Fra1

→ Matched with "HOMER.Jun_AP1", PSSM correlation = 0.830632620028121

→ Matching JASPAR.TCF12

→ Matched with "HOMER.Klf4", PSSM correlation = 0.604851333435436

→ Matching HOCOMOCO.AP2B_HUMAN.H11MO.0.B

→ Matched with "HOMER.E2F4", PSSM correlation = 0.586716764830023

→ Matching JASPAR.KLF1

→ Matched with "HOMER.Klf4", PSSM correlation = 0.695964622605546

→ Matching JASPAR.YER184C

→ Matched with "HOMER.E2F4", PSSM correlation = 0.582727090829179

→ Matching JASPAR.CST6

→ Matched with "HOMER.JunD", PSSM correlation = 0.727047767419962

→ Matching JASPAR.ZBTB32

→ Matched with "HOMER.HIF_1a", PSSM correlation = 0.629812991884604

→ Matching JASPAR.ZNF768

→ Matched with "HOMER.GAGA_repeat", PSSM correlation = 0.627668059047814

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
ℹ Extracting sequences...

ℹ Computing motif energies for 2470 intervals and 14001 normalization intervals

ℹ Inferring the model on 2470 intervals



Number of motifs: 10

R^2 train: 0.171

R^2 test: 0.172



→ Saving the model to "/net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper_raw/output/iq_3_pad_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg/iq_regression_model.rds"

ℹ Plotting 10 motifs

ℹ Plotting motif "E2F4"

ℹ Plotting motif "TATA_box"

ℹ Plotting motif "GAGA_repeat"

ℹ Plotting motif "Gata4"

ℹ Plotting motif "Klf4.2"

ℹ Plotting motif "JunD"

ℹ Plotting motif "Klf4"

ℹ Plotting motif "HIF_1a"

ℹ Plotting motif "E2F4.2"

ℹ Plotting motif "Jun_AP1"

ℹ Saving plot...

Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
✔ Plot saved to /net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper_raw/output/iq_3_pad_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg/iq_regression_model.pdf

→ Filtering the model

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
ℹ Using 1150 samples for filtering

ℹ R^2 of the full model: 0.10654154074023

ℹ Filtering features with R^2 < 5e-04 and bits < 1.75

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by TATA_box (------TAAA-----): 0.000819678934524004. Bits: 1.85161007093604

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by Gata4 (-------GATTA---): 0.00135179023248871. Bits: 2.89914309530711

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by Jun_AP1 (---TGACTCA-----): 0.000905809429341112. Bits: 3.757996805638

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by Klf4.2 (----C-C-CCCC---): 0.00397356475781445. Bits: 4.82205568205556

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by E2F4 (---TC-GCG------): 0.00681738891593635. Bits: 2.17961049825866

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by Klf4 (-CTCCGCCCCC----): 0.00261024174461011. Bits: 8.37529821422861

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by E2F4.2 (---GGCCG-------): -0.000180388757619512. Bits: 4.56620230887945

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by JunD (---GTGAC-T-A---): -0.00300137109959618. Bits: 4.29652181275864

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by HIF_1a (-----ATAC------): -0.000647538795479338. Bits: 2.89371160675043

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by GAGA_repeat (--C-GAGA-------): -5.88428457060086e-06. Bits: 2.43048949467008

ℹ Trying to remove the following features with R^2 < 5e-04: "E2F4.2", "JunD", "HIF_1a", and "GAGA_repeat"

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ Removing "HIF_1a" changed the R^2 by -0.000243586569296017

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”

Warning message:
“glmnet.fit: algorithm did not converge”
→ Removing "E2F4.2" changed the R^2 by -0.000652878072969043

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
→ Not removing "GAGA_repeat" (changed the R^2 by only 0.000735603015504224).

ℹ Removed 0 features with bits < 1.75

ℹ Removed 3 features with R^2 < 5e-04

Warning message in eval(family$initialize):
“non-integer #successes in a binomial glm!”
Warning message:
“glmnet.fit: algorithm did not converge”
✔ After filtering: Number of non-zero coefficients: 95 (out of 96). R^2: 0.168204873820012. Number of models: 7

ℹ Extracting sequences...

ℹ Computing motif energies for 2470 intervals and 14001 normalization intervals

ℹ Inferring the model on 2470 intervals



Number of motifs: 7

R^2 train: 0.168

R^2 test: 0.174



→ Saving the model to "/net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper_raw/output/iq_3_pad_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg/iq_regression_filtered_model.rds"

ℹ Plotting 7 motifs

ℹ Plotting motif "E2F4"

ℹ Plotting motif "Klf4.2"

ℹ Plotting motif "Klf4"

ℹ Plotting motif "Gata4"

ℹ Plotting motif "Jun_AP1"

ℹ Plotting motif "TATA_box"

ℹ Plotting motif "GAGA_repeat"

ℹ Saving plot...

Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
✔ Plot saved to /net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper_raw/output/iq_3_pad_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg/iq_regression_filtered_model.pdf

✔ Finished IQ regression



Run `plot_traj_model_report(traj_model)` to visualize the model features

Run `plot_prediction_scatter(traj_model)` to visualize the model predictions

<TrajectoryModel> with 7 motifs and 17 additional features

Slots include:
• @model: A GLM model object. Number of non-zero coefficients: 95
• @motif_models: A named list of motif models. Each element contains PSSM and
spatial model (7 models: "TATA_box", "Gata4", "Jun_AP1", "Klf4.2", "E2F4",
"Klf4", and "GAGA_repeat")
• @additional_features: A data frame of additional features (17 features)
• @coefs: A data frame of coefficients (24 elements)
• @model_features: A matrix of the model features (logistic functions of the
motif models energies, dimensions: 14001x96)
• @normalized_energies: A matrix of normalized energies of the model features
(dimensions: 14001x7)
• @type: A vector the length of the number of peaks, indicating whether each
peak is a training ('train') or a prediction peak ('test')
• @diff_score: A numeric value representing the difference score the model was
trained on (14001 elements)
• @predicted_diff_score: A numeric value representing the predicted difference
score
• @initial_prego_models: A list of prego models used in the initial phase of
the algorithm (5 models)
• @peak_intervals: A data frame containing the peak intervals (14001 elements)
• @normalization_intervals: A data frame containing the intervals used for
energy normalization (14001 elements)
• @features_r2: A numeric vector of the added R^2 values for each feature (7
elements)
• @params: A list of parameters used for training (including:
"energy_norm_quantile", "norm_energy_max", "min_energy", "alpha", "lambda",
"peaks_size", "spat_num_bins", "spat_bin_size", "n_clust_factor",
"include_interactions", "interaction_threshold", "symmetrize_spat", "seed",
"names_map", "stats", "features_bits", "r2_threshold", and "bits_threshold")

R^2 train: 0.168
R^2 test: 0.174

In [9]:
suffix <- "_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg"
run_iq_regression(
    model_type = "5",
    cgd = cgd,
    test_idxs = test_idxs,
    train_idxs = train_idxs,
    suffix = suffix
)
run_iq_regression(
    model_type = "3",
    cgd = cgd,
    test_idxs = test_idxs,
    train_idxs = train_idxs,
    suffix = suffix
)
run_iq_regression(
    model_type = "5_pad",
    cgd = cgd,
    test_idxs = test_idxs,
    train_idxs = train_idxs,
    suffix = suffix
)
run_iq_regression(
    model_type = "3_pad",
    cgd = cgd,
    test_idxs = test_idxs,
    train_idxs = train_idxs,
    suffix = suffix
)

→ Computing sequence features

ℹ Seed: 60427

ℹ Training on 6354 intervals (81%) and testing on 1460 intervals (19%)

ℹ Saving the train and test indices to "/net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper/output/iq_5_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg"

ℹ Learning prego motifs (de-novo motifs)

ℹ Extracting sequences...

ℹ Inferring 5 prego motifs...

ℹ Using 15 bins of size 40 bp

ℹ Running regression for 5 motifs



── Running first regression ──



ℹ Using 15 bins of size 40 bp

ℹ Using "ks" as the final metric

ℹ Number of response variables: 1

ℹ Performing sampled optimization

ℹ Sampling 1 of the dataset

ℹ Stratified sampling

ℹ sampled 1973 zeros and 4381 ones

ℹ Sampling 0.1 of the dataset

ℹ Stratified sampling

ℹ sampled 197 zeros and 438 ones



── Generate candidate kmers



── Regress each candidate kmer on sampled data

ℹ Running regression on 9 candidate kmers

• Bidirectional: TRUE

• Spat bin size: 40

• Number of spatial bins 15

• Length of sequence: 600

• Min gap: 0

• Max gap: 1

• Kmer length: 8

• Improve epsilon: 0.0001

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

ℹ Performing regression on full data

ℹ Using 15 bins of size 40 bp

ℹ Using "ks" as the final metric

ℹ Number of response variables: 1

ℹ Motif is shorter than 15, extending with wildcards

ℹ Initializing regression with the following motif: "***CCGGAAGT****"

ℹ Running regression

• Motif length: 15

• Bidirectional: TRUE

• Spat min: 0

• Spat max: 600

• Spat bin size: 40

• Number of bins: 15

• Improve epsilon: 0.0001

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

✔ Finished running regression. Consensus: "CG"

✔ KS test D: 0.4199, p-value: 0

ℹ Best motif: "***CCGGAAGT****", score (ks): 0.438750202813898



── Running regression #2 ──



ℹ Using 15 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Performing sampled optimization

ℹ Sampling 1 of the dataset

✔ Sampled 6010 rows from the data frame.

ℹ Sampling 0.1 of the dataset

✔ Sampled 600 rows from the data frame.



── Generate candidate kmers



── Regress each candidate kmer on sampled data

ℹ Running regression on 6 candidate kmers

• Bidirectional: TRUE

• Spat bin size: 40

• Number of spatial bins 15

• Length of sequence: 600

• Min gap: 0

• Max gap: 1

• Kmer length: 8

• Improve epsilon: 0.0001

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call

ℹ Performing regression on full data

ℹ Using 15 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Motif is shorter than 15, extending with wildcards

ℹ Initializing regression with the following motif: "***CGCA*GCGC***"

ℹ Running regression

• Motif length: 15

• Bidirectional: TRUE

• Spat min: 0

• Spat max: 600

• Spat bin size: 40

• Number of bins: 15

• Improve epsilon: 0.0001

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

✔ Finished running regression. Consensus: "GMGCA*GCGC"

✔ R^2: 0.0143

ℹ Best motif: "***CGCA*GCGC***", score (r2): 0.0159218532385309

ℹ KS statistic: 0.125410688670482

ℹ KS test statistic for models 1 and 2: 0.440336924652635

ℹ Improvement in KS test statistic: 0.0204282580876991



── Running regression #3 ──



ℹ Using 15 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Performing sampled optimization

ℹ Sampling 1 of the dataset

✔ Sampled 5230 rows from the data frame.

ℹ Sampling 0.1 of the dataset

✔ Sampled 520 rows from the data frame.



── Generate candidate kmers

ℹ Could not find any kmer when using a threshold of 0.08. Trying with 0.04



── Regress each candidate kmer on sampled data

ℹ Running regression on 1 candidate kmers

• Bidirectional: TRUE

• Spat bin size: 40

• Number of spatial bins 15

• Length of sequence: 600

• Min gap: 0

• Max gap: 1

• Kmer length: 8

• Improve epsilon: 0.0001

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

→ regressing with seed: "AA*ATGGCG"

→ "AA*ATGGCG", score (r2): 0.0314512009391249, validation score (r2): 0.0132640229222951

ℹ Performing regression on full data

ℹ Using 15 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Motif is shorter than 15, extending with wildcards

ℹ Initializing regression with the following motif: "***AA*ATGGCG***"

ℹ Running regression

• Motif length: 15

• Bidirectional: TRUE

• Spat min: 0

• Spat max: 600

• Spat bin size: 40

• Number of bins: 15

• Improve epsilon: 0.0001

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

✔ Finished running regression. Consensus: "ATRG"

✔ R^2: 0.0276

ℹ Best motif: "***AA*ATGGCG***", score (r2): 0.0132640229222951

ℹ KS statistic: 0.197694671259909

ℹ KS test statistic for models 1, 2, and 3: 0.462086258532647

ℹ Improvement in KS test statistic: 0.021749333880012



── Running regression #4 ──



ℹ Using 15 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Performing sampled optimization

ℹ Sampling 1 of the dataset

✔ Sampled 5640 rows from the data frame.

ℹ Sampling 0.1 of the dataset

✔ Sampled 560 rows from the data frame.



── Generate candidate kmers

ℹ Could not find any kmer when using a threshold of 0.08. Trying with 0.04



── Regress each candidate kmer on sampled data

ℹ Running regression on 1 candidate kmers

• Bidirectional: TRUE

• Spat bin size: 40

• Number of spatial bins 15

• Length of sequence: 600

• Min gap: 0

• Max gap: 1

• Kmer length: 8

• Improve epsilon: 0.0001

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

→ regressing with seed: "GCCCC*CCC"

→ "GCCCC*CCC", score (r2): 0.0248192293385364, validation score (r2): 0.00071868735985771

ℹ Performing regression on full data

ℹ Using 15 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Motif is shorter than 15, extending with wildcards

ℹ Initializing regression with the following motif: "***GCCCC*CCC***"

ℹ Running regression

• Motif length: 15

• Bidirectional: TRUE

• Spat min: 0

• Spat max: 600

• Spat bin size: 40

• Number of bins: 15

• Improve epsilon: 0.0001

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

✔ Finished running regression. Consensus: "C**CCC*Y"

✔ R^2: 0.0281

ℹ Best motif: "***GCCCC*CCC***", score (r2): 0.00071868735985771

ℹ KS statistic: 0.193179713394001

ℹ KS test statistic for models 1, 2, 3, and 4: 0.492699838599454

ℹ Improvement in KS test statistic: 0.0306135800668069



── Running regression #5 ──



ℹ Using 15 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Performing sampled optimization

ℹ Sampling 1 of the dataset

✔ Sampled 5800 rows from the data frame.

ℹ Sampling 0.1 of the dataset

✔ Sampled 580 rows from the data frame.



── Generate candidate kmers

ℹ Could not find any kmer when using a threshold of 0.08. Trying with 0.04



── Regress each candidate kmer on sampled data

ℹ Running regression on 1 candidate kmers

• Bidirectional: TRUE

• Spat bin size: 40

• Number of spatial bins 15

• Length of sequence: 600

• Min gap: 0

• Max gap: 1

• Kmer length: 8

• Improve epsilon: 0.0001

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

→ regressing with seed: "TGTG*CGTG"

→ "TGTG*CGTG", score (r2): 0.000522896410783619, validation score (r2): 0.0000330108584103186

ℹ Performing regression on full data

ℹ Using 15 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Motif is shorter than 15, extending with wildcards

ℹ Initializing regression with the following motif: "***TGTG*CGTG***"

ℹ Running regression

• Motif length: 15

• Bidirectional: TRUE

• Spat min: 0

• Spat max: 600

• Spat bin size: 40

• Number of bins: 15

• Improve epsilon: 0.0001

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

✔ Finished running regression. Consensus: "T*TG*CGTG"

✔ R^2: 0.0025

ℹ Best motif: "***TGTG*CGTG***", score (r2): 0.0000330108584103186

ℹ KS statistic: 0.032808701538332

ℹ KS test statistic for models 1, 2, 3, 4, and 5: 0.494978836062697

ℹ Improvement in KS test statistic: 0.00227899746324295

✔ Best model: model #1 (score of 0.419908666564936)

→ Saving the prego model to "/net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper/output/iq_5_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg/prego_model.rds"

→ Regressing on train set

ℹ Number of peaks: 6354

→ Extracting sequences...

ℹ Calculating correlations between 21867 motif energies and ATAC difference...

ℹ Selected 219 (out of 21867) features with absolute correlation >= 0.15

ℹ Running first round of regression, # of features: 219

Warning message:
“glmnet.fit: algorithm did not converge”
ℹ Taking 190 features with beta >= 0.01

ℹ Running second round of regression...

Warning message:
“glmnet.fit: algorithm did not converge”
ℹ Clustering 189 features into 10 clusters...

ℹ Choosing top 10 features clusters

ℹ Features left: 189

ℹ Learning a model for each motif cluster...

R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call

ℹ Infering energies...

ℹ Running final regression, number of features: 108

✔ Finished running model. Number of non-zero coefficients: 108 (out of 108). R^2: 0.33762130834668

→ Matching SCENIC.cisbp__M02599

→ Matched with "HOMER.Elk4", PSSM correlation = 0.717623902313311

→ Matching JASPAR.Fli-Erg-c

→ Matched with "HOMER.ETS1", PSSM correlation = 0.885306330928511

→ Matching SCENIC.transfac_public__M00039

→ Matched with "HOMER.Atf7", PSSM correlation = 0.618162092565979

→ Matching SCENIC.flyfactorsurvey__phol_SANGER_5_FBgn0035997

→ Matched with "HOMER.YY1", PSSM correlation = 0.80340613013752

→ Matching SCENIC.homer__GGCCCCGCCCCC_Sp1

→ Matched with "HOMER.KLF5", PSSM correlation = 0.800044715138123

→ Matching SCENIC.elemento__TTCCGCC

→ Matched with "HOMER.ETS", PSSM correlation = 0.617312971896137

→ Matching e2

→ Matched with "HOMER.NRF1", PSSM correlation = 0.883282215680623

→ Matching SCENIC.dbtfbs__ETV5_HepG2_ENCSR096IIB_merged_N1

→ Matched with "HOMER.Elk1", PSSM correlation = 0.639395788103266

→ Matching SCENIC.yetfasco__YCR106W_506

→ Matched with "HOMER.Egr1", PSSM correlation = 0.509873260447389

→ Matching HOMER.GAGA_repeat

→ Matched with "HOMER.GATA3_1", PSSM correlation = 0.582468988030693

ℹ Extracting sequences...

ℹ Computing motif energies for 1460 intervals and 7814 normalization intervals

ℹ Inferring the model on 1460 intervals



Number of motifs: 10

R^2 train: 0.338

R^2 test: 0.3



→ Saving the model to "/net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper/output/iq_5_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg/iq_regression_model.rds"

ℹ Plotting 10 motifs

Warning message:
“The `<scale>` argument of `guides()` cannot be `FALSE`. Use "none" instead as
of ggplot2 3.3.4.
ℹ The deprecated feature was likely used in the ggseqlogo package.
  Please report the issue at <https://github.com/omarwagih/ggseqlogo/issues>.”
ℹ Plotting motif "NRF1"

ℹ Plotting motif "KLF5"

ℹ Plotting motif "YY1"

ℹ Plotting motif "ETS1"

ℹ Plotting motif "Atf7"

ℹ Plotting motif "Egr1"

ℹ Plotting motif "Elk4"

ℹ Plotting motif "GATA3_1"

ℹ Plotting motif "Elk1"

ℹ Plotting motif "ETS"

R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call

Warning message in ks.test.default(plot_df$observed[plot_df$energy == "0-3"], plot_df$observed[plot_df$energy == :
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(plot_df$observed[plot_df$energy == "0-3"], plot_df$observed[plot_df$energy == :
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(plot_df$observed[plot_df$energy == "0-3"], plot_df$observed[plot_df$energy == :
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(plot_df$observed[plot_df$energy == "0-3"], plot_df$observed[plot_df$energy == :
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(plot_df$observed[plot_df$energy == "0-3"], plot_df$observed[plot_df$energy == :
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(plot_df$observed[plot_df$energy == "0-3"], plot_df$observed[plot_df$energy == :
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(plot_df$observed[plot_df$energy == "0-3"], plot_df$observed[plot_df$energy == :
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(plot_df$observed[plot_df$energy == "0-3"], plot_df$observed[plot_df$energy == :
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(plot_df$observed[plot_df$energy == "0-3"], plot_df$observed[plot_df$energy == :
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(plot_df$observed[plot_df$energy == "0-3"], plot_df$observed[plot_df$energy == :
“p-value will be approximate in the presence of ties”
ℹ Saving plot...

Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 36 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
✔ Plot saved to /net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper/output/iq_5_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg/iq_regression_model.pdf

→ Filtering the model

Warning message:
“glmnet.fit: algorithm did not converge”
ℹ Using 63 samples for filtering

ℹ R^2 of the full model: 0.102108938017657

ℹ Filtering features with R^2 < 0.0005 and bits < 1.75

Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by Elk4 (--------CGG----): 0.0201340980766112. Bits: 2.88661058309781

Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by ETS1 (---C-GGAAGT----): 0.00822554737345987. Bits: 4.18146878937753

Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by Atf7 (-------CG------): -0.0000240031122028805. Bits: 1.78633444884717

→ R^2 added by YY1 (---A--ATGGC----): 0.0169345981440832. Bits: 4.03728041661004

Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by KLF5 (-A-GGGCGGA-C---): 0.0158686161181328. Bits: 4.44467938386631

→ R^2 added by ETS (---GGCGGAA-----): -0.00355090712244392. Bits: 5.78093239816793

Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by NRF1 (---GCGCA-GCGC--): 0.00411903827317575. Bits: 7.6539352973561

Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by Elk1 (-----ACTTCC-CA-): -0.0043529969924325. Bits: 6.07875035006573

Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by Egr1 (---------A-----): -0.000557292035091125. Bits: 0.902619622495869

Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by GATA3_1 (-GAGAGAGAG): 0.00145639269747593. Bits: 4.53682146581966

ℹ Removing the following features with bits < 1.75: "Egr1"

ℹ Trying to remove the following features with R^2 < 0.0005: "Atf7", "ETS", "Elk1", and "Egr1"

Warning message:
“glmnet.fit: algorithm did not converge”
Warning message:
“glmnet.fit: algorithm did not converge”
→ Removing "ETS" changed the R^2 by -0.00989321062854101

Warning message:
“glmnet.fit: algorithm did not converge”
→ Not removing "Atf7" (changed the R^2 by only 0.00389471920158524).

ℹ Removed 1 features with bits < 1.75

ℹ Removed 2 features with R^2 < 0.0005

✔ After filtering: Number of non-zero coefficients: 95 (out of 96). R^2: 0.33486015840096. Number of models: 7

ℹ Extracting sequences...

ℹ Computing motif energies for 1460 intervals and 7814 normalization intervals

ℹ Inferring the model on 1460 intervals



Number of motifs: 7

R^2 train: 0.335

R^2 test: 0.297



→ Saving the model to "/net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper/output/iq_5_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg/iq_regression_filtered_model.rds"

ℹ Plotting 7 motifs

ℹ Plotting motif "Elk4"

ℹ Plotting motif "YY1"

ℹ Plotting motif "KLF5"

ℹ Plotting motif "ETS1"

ℹ Plotting motif "NRF1"

ℹ Plotting motif "GATA3_1"

ℹ Plotting motif "Atf7"

R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call

Warning message in ks.test.default(plot_df$observed[plot_df$energy == "0-3"], plot_df$observed[plot_df$energy == :
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(plot_df$observed[plot_df$energy == "0-3"], plot_df$observed[plot_df$energy == :
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(plot_df$observed[plot_df$energy == "0-3"], plot_df$observed[plot_df$energy == :
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(plot_df$observed[plot_df$energy == "0-3"], plot_df$observed[plot_df$energy == :
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(plot_df$observed[plot_df$energy == "0-3"], plot_df$observed[plot_df$energy == :
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(plot_df$observed[plot_df$energy == "0-3"], plot_df$observed[plot_df$energy == :
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(plot_df$observed[plot_df$energy == "0-3"], plot_df$observed[plot_df$energy == :
“p-value will be approximate in the presence of ties”
ℹ Saving plot...

Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 36 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
✔ Plot saved to /net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper/output/iq_5_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg/iq_regression_filtered_model.pdf

✔ Finished IQ regression



Run `plot_traj_model_report(traj_model)` to visualize the model features

Run `plot_prediction_scatter(traj_model)` to visualize the model predictions

<TrajectoryModel> with 7 motifs and 17 additional features

Slots include:
• @model: A GLM model object. Number of non-zero coefficients: 95
• @motif_models: A named list of motif models. Each element contains PSSM and
spatial model (7 models: "Elk4", "ETS1", "Atf7", "YY1", "KLF5", "NRF1", and
"GATA3_1")
• @additional_features: A data frame of additional features (17 features)
• @coefs: A data frame of coefficients (24 elements)
• @model_features: A matrix of the model features (logistic functions of the
motif models energies, dimensions: 7814x96)
• @normalized_energies: A matrix of normalized energies of the model features
(dimensions: 7814x7)
• @type: A vector the length of the number of peaks, indicating whether each
peak is a training ('train') or a prediction peak ('test')
• @diff_score: A numeric value representing the difference score the model was
trained on (7814 elements)
• @predicted_diff_score: A numeric value representing the predicted difference
score
• @initial_prego_models: A list of prego models used in the initial phase of
the algorithm (5 models)
• @peak_intervals: A data frame containing the peak intervals (7814 elements)
• @normalization_intervals: A data frame containing the intervals used for
energy normalization (7814 elements)
• @features_r2: A numeric vector of the added R^2 values for each feature (7
elements)
• @params: A list of parameters used for training (including:
"energy_norm_quantile", "norm_energy_max", "min_energy", "alpha", "lambda",
"peaks_size", "spat_num_bins", "spat_bin_size", "n_clust_factor",
"include_interactions", "interaction_threshold", "symmetrize_spat", "seed",
"names_map", "stats", "features_bits", "r2_threshold", and "bits_threshold")

R^2 train: 0.335
R^2 test: 0.297

→ Computing sequence features

ℹ Seed: 60427

ℹ Training on 6354 intervals (81%) and testing on 1460 intervals (19%)

ℹ Saving the train and test indices to "/net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper/output/iq_3_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg"

ℹ Learning prego motifs (de-novo motifs)

ℹ Extracting sequences...

ℹ Inferring 5 prego motifs...

ℹ Using 15 bins of size 40 bp

ℹ Running regression for 5 motifs



── Running first regression ──



ℹ Using 15 bins of size 40 bp

ℹ Using "ks" as the final metric

ℹ Number of response variables: 1

ℹ Performing sampled optimization

ℹ Sampling 1 of the dataset

ℹ Stratified sampling

ℹ sampled 1973 zeros and 4381 ones

ℹ Sampling 0.1 of the dataset

ℹ Stratified sampling

ℹ sampled 197 zeros and 438 ones



── Generate candidate kmers



── Regress each candidate kmer on sampled data

ℹ Running regression on 7 candidate kmers

• Bidirectional: TRUE

• Spat bin size: 40

• Number of spatial bins 15

• Length of sequence: 600

• Min gap: 0

• Max gap: 1

• Kmer length: 8

• Improve epsilon: 0.0001

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call

ℹ Performing regression on full data

ℹ Using 15 bins of size 40 bp

ℹ Using "ks" as the final metric

ℹ Number of response variables: 1

ℹ Motif is shorter than 15, extending with wildcards

ℹ Initializing regression with the following motif: "***GGGG*CGGG***"

ℹ Running regression

• Motif length: 15

• Bidirectional: TRUE

• Spat min: 0

• Spat max: 600

• Spat bin size: 40

• Number of bins: 15

• Improve epsilon: 0.0001

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

✔ Finished running regression. Consensus: "CG"

✔ KS test D: 0.3841, p-value: 0

ℹ Best motif: "***GGGG*CGGG***", score (ks): 0.464814686044086



── Running regression #2 ──



ℹ Using 15 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Performing sampled optimization

ℹ Sampling 1 of the dataset

✔ Sampled 5080 rows from the data frame.

ℹ Sampling 0.1 of the dataset

✔ Sampled 500 rows from the data frame.



── Generate candidate kmers

ℹ Could not find any kmer when using a threshold of 0.08. Trying with 0.04



── Regress each candidate kmer on sampled data

ℹ Running regression on 1 candidate kmers

• Bidirectional: TRUE

• Spat bin size: 40

• Number of spatial bins 15

• Length of sequence: 600

• Min gap: 0

• Max gap: 1

• Kmer length: 8

• Improve epsilon: 0.0001

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

→ regressing with seed: "TGCGC*CCC"

→ "TGCGC*CCC", score (r2): 0.0168308163697445, validation score (r2): 0.0000301091689344347

ℹ Performing regression on full data

ℹ Using 15 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Motif is shorter than 15, extending with wildcards

ℹ Initializing regression with the following motif: "***TGCGC*CCC***"

ℹ Running regression

• Motif length: 15

• Bidirectional: TRUE

• Spat min: 0

• Spat max: 600

• Spat bin size: 40

• Number of bins: 15

• Improve epsilon: 0.0001

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

✔ Finished running regression. Consensus: "TGCGC*CC"

✔ R^2: 0.0127

ℹ Best motif: "***TGCGC*CCC***", score (r2): 0.0000301091689344347

ℹ KS statistic: 0.000506842372022301

ℹ KS test statistic for models 1 and 2: 0.3988656263807

ℹ Improvement in KS test statistic: 0.0147774457573961



── Running regression #3 ──



ℹ Using 15 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Performing sampled optimization

ℹ Sampling 1 of the dataset

✔ Sampled 5490 rows from the data frame.

ℹ Sampling 0.1 of the dataset

✔ Sampled 540 rows from the data frame.



── Generate candidate kmers

ℹ Could not find any kmer when using a threshold of 0.08. Trying with 0.04



── Regress each candidate kmer on sampled data

ℹ Running regression on 1 candidate kmers

• Bidirectional: TRUE

• Spat bin size: 40

• Number of spatial bins 15

• Length of sequence: 600

• Min gap: 0

• Max gap: 1

• Kmer length: 8

• Improve epsilon: 0.0001

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

→ regressing with seed: "CT*CATGCG"

→ "CT*CATGCG", score (r2): 0.0280657645894908, validation score (r2): 0.000713914721363319

ℹ Performing regression on full data

ℹ Using 15 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Motif is shorter than 15, extending with wildcards

ℹ Initializing regression with the following motif: "***CT*CATGCG***"

ℹ Running regression

• Motif length: 15

• Bidirectional: TRUE

• Spat min: 0

• Spat max: 600

• Spat bin size: 40

• Number of bins: 15

• Improve epsilon: 0.0001

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

✔ Finished running regression. Consensus: "T**ATGCG"

✔ R^2: 0.0099

ℹ Best motif: "***CT*CATGCG***", score (r2): 0.000713914721363319

ℹ KS statistic: -1.89193279098721e-17

ℹ KS test statistic for models 1, 2, and 3: 0.420205182657036

ℹ Improvement in KS test statistic: 0.0213395562763363



── Running regression #4 ──



ℹ Using 15 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Performing sampled optimization

ℹ Sampling 1 of the dataset

✔ Sampled 5960 rows from the data frame.

ℹ Sampling 0.1 of the dataset

✔ Sampled 590 rows from the data frame.



── Generate candidate kmers

ℹ Could not find any kmer when using a threshold of 0.08. Trying with 0.04



── Regress each candidate kmer on sampled data

ℹ Running regression on 1 candidate kmers

• Bidirectional: TRUE

• Spat bin size: 40

• Number of spatial bins 15

• Length of sequence: 600

• Min gap: 0

• Max gap: 1

• Kmer length: 8

• Improve epsilon: 0.0001

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

→ regressing with seed: "GCGCATGC"

→ "GCGCATGC", score (r2): 0.00468996528954525, validation score (r2): 0.00227134987166004

ℹ Performing regression on full data

ℹ Using 15 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Motif is shorter than 15, extending with wildcards

ℹ Initializing regression with the following motif: "***GCGCATGC****"

ℹ Running regression

• Motif length: 15

• Bidirectional: TRUE

• Spat min: 0

• Spat max: 600

• Spat bin size: 40

• Number of bins: 15

• Improve epsilon: 0.0001

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

✔ Finished running regression. Consensus: "GCGCA*GC"

✔ R^2: 0.0042

ℹ Best motif: "***GCGCATGC****", score (r2): 0.00227134987166004

ℹ KS statistic: 0.0525352935711771

ℹ KS test statistic for models 1, 2, 3, and 4: 0.417058039756757

ℹ Improvement in KS test statistic: -0.00314714290027907



── Running regression #5 ──



ℹ Using 15 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Performing sampled optimization

ℹ Sampling 1 of the dataset

✔ Sampled 5040 rows from the data frame.

ℹ Sampling 0.1 of the dataset

✔ Sampled 500 rows from the data frame.



── Generate candidate kmers

ℹ Could not find any kmer when using a threshold of 0.08. Trying with 0.04



── Regress each candidate kmer on sampled data

ℹ Running regression on 1 candidate kmers

• Bidirectional: TRUE

• Spat bin size: 40

• Number of spatial bins 15

• Length of sequence: 600

• Min gap: 0

• Max gap: 1

• Kmer length: 8

• Improve epsilon: 0.0001

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

→ regressing with seed: "CTGTCT*TG"

→ "CTGTCT*TG", score (r2): 0.0394786529698661, validation score (r2): 0.00504053068879549

ℹ Performing regression on full data

ℹ Using 15 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Motif is shorter than 15, extending with wildcards

ℹ Initializing regression with the following motif: "***CTGTCT*TG***"

ℹ Running regression

• Motif length: 15

• Bidirectional: TRUE

• Spat min: 0

• Spat max: 600

• Spat bin size: 40

• Number of bins: 15

• Improve epsilon: 0.0001

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

✔ Finished running regression. Consensus: "M**TC"

✔ R^2: 0.0292

ℹ Best motif: "***CTGTCT*TG***", score (r2): 0.00504053068879549

ℹ KS statistic: -1.89193279098721e-17

ℹ KS test statistic for models 1, 2, 3, 4, and 5: 0.431684624420084

ℹ Improvement in KS test statistic: 0.0146265846633269

✔ Best model: model #1 (score of 0.384088180623304)

→ Saving the prego model to "/net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper/output/iq_3_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg/prego_model.rds"

→ Regressing on train set

ℹ Number of peaks: 6354

→ Extracting sequences...

ℹ Calculating correlations between 21867 motif energies and ATAC difference...

ℹ Selected 141 (out of 21867) features with absolute correlation >= 0.15

ℹ Running first round of regression, # of features: 141

ℹ Taking 133 features with beta >= 0.01

ℹ Running second round of regression...

ℹ Clustering 133 features into 10 clusters...

ℹ Choosing top 10 features clusters

ℹ Features left: 133

ℹ Learning a model for each motif cluster...

R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call

ℹ Infering energies...

ℹ Running final regression, number of features: 108

✔ Finished running model. Number of non-zero coefficients: 107 (out of 108). R^2: 0.370272307044605

→ Matching SCENIC.cisbp__M02599

→ Matched with "HOMER.Unknown3_1", PSSM correlation = 0.652419209224668

→ Matching JOLMA.GABPA_mono_full

→ Matched with "HOMER.GABPA", PSSM correlation = 0.898677178173918

→ Matching SCENIC.cisbp__M00094

→ Matched with "HOMER.Elk1", PSSM correlation = 0.586206897196859

→ Matching SCENIC.scertf__harbison.SUT1

→ Matched with "HOMER.ZNF711", PSSM correlation = 0.615949553936897

→ Matching JOLMA.YY2_mono_full

→ Matched with "HOMER.YY1", PSSM correlation = 0.899692577879752

→ Matching SCENIC.flyfactorsurvey__btd_NAR_FBgn0000233

→ Matched with "HOMER.KLF5", PSSM correlation = 0.856140765086805

→ Matching SCENIC.cisbp__M07953

→ Matched with "HOMER.ETV1", PSSM correlation = 0.76211474493952

→ Matching SCENIC.predrem__nrMotif2157

→ Matched with "HOMER.Srebp2", PSSM correlation = 0.624254455429031

→ Matching e2

→ Matched with "HOMER.LIN_15B", PSSM correlation = 0.590950169048716

→ Matching e5

→ Matched with "HOMER.FOXA1", PSSM correlation = 0.517261195321616

ℹ Extracting sequences...

ℹ Computing motif energies for 1460 intervals and 7814 normalization intervals

ℹ Inferring the model on 1460 intervals



Number of motifs: 10

R^2 train: 0.37

R^2 test: 0.306



→ Saving the model to "/net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper/output/iq_3_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg/iq_regression_model.rds"

ℹ Plotting 10 motifs

ℹ Plotting motif "Unknown3_1"

ℹ Plotting motif "GABPA"

ℹ Plotting motif "FOXA1"

ℹ Plotting motif "ZNF711"

ℹ Plotting motif "LIN_15B"

ℹ Plotting motif "KLF5"

ℹ Plotting motif "YY1"

ℹ Plotting motif "ETV1"

ℹ Plotting motif "Srebp2"

ℹ Plotting motif "Elk1"

R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call

Warning message in ks.test.default(plot_df$observed[plot_df$energy == "0-3"], plot_df$observed[plot_df$energy == :
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(plot_df$observed[plot_df$energy == "0-3"], plot_df$observed[plot_df$energy == :
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(plot_df$observed[plot_df$energy == "0-3"], plot_df$observed[plot_df$energy == :
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(plot_df$observed[plot_df$energy == "0-3"], plot_df$observed[plot_df$energy == :
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(plot_df$observed[plot_df$energy == "0-3"], plot_df$observed[plot_df$energy == :
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(plot_df$observed[plot_df$energy == "0-3"], plot_df$observed[plot_df$energy == :
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(plot_df$observed[plot_df$energy == "0-3"], plot_df$observed[plot_df$energy == :
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(plot_df$observed[plot_df$energy == "0-3"], plot_df$observed[plot_df$energy == :
“p-value will be approximate in the presence of ties”
ℹ Saving plot...

Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 30 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
✔ Plot saved to /net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper/output/iq_3_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg/iq_regression_model.pdf

→ Filtering the model

ℹ Using 63 samples for filtering

ℹ R^2 of the full model: 0.174525516745151

ℹ Filtering features with R^2 < 0.0005 and bits < 1.75

→ R^2 added by Unknown3_1 (---------CGG---): 0.00251245718380746. Bits: 4.73306858864156

→ R^2 added by GABPA (----CCGGAAG----): 0.00117063258914343. Bits: 4.34896890676674

Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by Elk1 (-----ACG-------): 0.0355995705977823. Bits: 1.87108764395845

→ R^2 added by ZNF711 (----CGG--------): 0.0000747894637732893. Bits: 3.54342944571108

→ R^2 added by YY1 (------ATGGC----): 0.000133215748832183. Bits: 3.48177004425918

→ R^2 added by KLF5 (---GGGCGG------): -0.0000757899309839216. Bits: 5.06796986056839

Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by ETV1 (----GGAAGTG----): 0.0127612099716003. Bits: 4.04981997068063

→ R^2 added by Srebp2 (--CAGG-): 0.00854379768514679. Bits: 3.59715116877487

Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by LIN_15B (---GGG-GCGCA-T-): 0.000237962871650538. Bits: 8.91044062216651

Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by FOXA1 (---C--AGACAG---): 0.0395817782176418. Bits: 3.74177243987167

ℹ Trying to remove the following features with R^2 < 0.0005: "ZNF711", "YY1", "KLF5", and "LIN_15B"

→ Removing "ZNF711" changed the R^2 by 0.0000357879139077366

→ Removing "YY1" changed the R^2 by 0.000216475075733191

Warning message:
“glmnet.fit: algorithm did not converge”
→ Removing "LIN_15B" changed the R^2 by 0.000217390097614067

ℹ Removed 0 features with bits < 1.75

ℹ Removed 4 features with R^2 < 0.0005

✔ After filtering: Number of non-zero coefficients: 90 (out of 92). R^2: 0.32701937887925. Number of models: 6

ℹ Extracting sequences...

ℹ Computing motif energies for 1460 intervals and 7814 normalization intervals

ℹ Inferring the model on 1460 intervals



Number of motifs: 6

R^2 train: 0.327

R^2 test: 0.279



→ Saving the model to "/net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper/output/iq_3_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg/iq_regression_filtered_model.rds"

ℹ Plotting 6 motifs

ℹ Plotting motif "FOXA1"

ℹ Plotting motif "Elk1"

ℹ Plotting motif "ETV1"

ℹ Plotting motif "Srebp2"

ℹ Plotting motif "Unknown3_1"

ℹ Plotting motif "GABPA"

R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call

Warning message in ks.test.default(plot_df$observed[plot_df$energy == "0-3"], plot_df$observed[plot_df$energy == :
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(plot_df$observed[plot_df$energy == "0-3"], plot_df$observed[plot_df$energy == :
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(plot_df$observed[plot_df$energy == "0-3"], plot_df$observed[plot_df$energy == :
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(plot_df$observed[plot_df$energy == "0-3"], plot_df$observed[plot_df$energy == :
“p-value will be approximate in the presence of ties”
ℹ Saving plot...

Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 30 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
✔ Plot saved to /net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper/output/iq_3_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg/iq_regression_filtered_model.pdf

✔ Finished IQ regression



Run `plot_traj_model_report(traj_model)` to visualize the model features

Run `plot_prediction_scatter(traj_model)` to visualize the model predictions

<TrajectoryModel> with 6 motifs and 17 additional features

Slots include:
• @model: A GLM model object. Number of non-zero coefficients: 90
• @motif_models: A named list of motif models. Each element contains PSSM and
spatial model (6 models: "Unknown3_1", "GABPA", "Elk1", "ETV1", "Srebp2", and
"FOXA1")
• @additional_features: A data frame of additional features (17 features)
• @coefs: A data frame of coefficients (23 elements)
• @model_features: A matrix of the model features (logistic functions of the
motif models energies, dimensions: 7814x92)
• @normalized_energies: A matrix of normalized energies of the model features
(dimensions: 7814x6)
• @type: A vector the length of the number of peaks, indicating whether each
peak is a training ('train') or a prediction peak ('test')
• @diff_score: A numeric value representing the difference score the model was
trained on (7814 elements)
• @predicted_diff_score: A numeric value representing the predicted difference
score
• @initial_prego_models: A list of prego models used in the initial phase of
the algorithm (5 models)
• @peak_intervals: A data frame containing the peak intervals (7814 elements)
• @normalization_intervals: A data frame containing the intervals used for
energy normalization (7814 elements)
• @features_r2: A numeric vector of the added R^2 values for each feature (6
elements)
• @params: A list of parameters used for training (including:
"energy_norm_quantile", "norm_energy_max", "min_energy", "alpha", "lambda",
"peaks_size", "spat_num_bins", "spat_bin_size", "n_clust_factor",
"include_interactions", "interaction_threshold", "symmetrize_spat", "seed",
"names_map", "stats", "features_bits", "r2_threshold", and "bits_threshold")

R^2 train: 0.327
R^2 test: 0.279

→ Computing sequence features

ℹ Seed: 60427

ℹ Training on 6354 intervals (81%) and testing on 1460 intervals (19%)

ℹ Saving the train and test indices to "/net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper/output/iq_5_pad_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg"

ℹ Learning prego motifs (de-novo motifs)

ℹ Extracting sequences...

ℹ Inferring 5 prego motifs...

ℹ Using 11 bins of size 40 bp

ℹ Running regression for 5 motifs



── Running first regression ──



ℹ Using 11 bins of size 40 bp

ℹ Using "ks" as the final metric

ℹ Number of response variables: 1

ℹ Performing sampled optimization

ℹ Sampling 1 of the dataset

ℹ Stratified sampling

ℹ sampled 1973 zeros and 4381 ones

ℹ Sampling 0.1 of the dataset

ℹ Stratified sampling

ℹ sampled 197 zeros and 438 ones



── Generate candidate kmers



── Regress each candidate kmer on sampled data

ℹ Running regression on 8 candidate kmers

• Bidirectional: TRUE

• Spat bin size: 40

• Number of spatial bins 11

• Length of sequence: 440

• Min gap: 0

• Max gap: 1

• Kmer length: 8

• Improve epsilon: 0.0001

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call

ℹ Performing regression on full data

ℹ Using 11 bins of size 40 bp

ℹ Using "ks" as the final metric

ℹ Number of response variables: 1

ℹ Motif is shorter than 15, extending with wildcards

ℹ Initializing regression with the following motif: "***GA*TACAGG***"

ℹ Running regression

• Motif length: 15

• Bidirectional: TRUE

• Spat min: 30

• Spat max: 470

• Spat bin size: 40

• Number of bins: 11

• Improve epsilon: 0.0001

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

✔ Finished running regression. Consensus: NA

✔ KS test D: 0.3931, p-value: 0

ℹ Best motif: "***GA*TACAGG***", score (ks): 0.410286720904898



── Running regression #2 ──



ℹ Using 11 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Performing sampled optimization

ℹ Sampling 1 of the dataset

✔ Sampled 5790 rows from the data frame.

ℹ Sampling 0.1 of the dataset

✔ Sampled 570 rows from the data frame.



── Generate candidate kmers

ℹ Could not find any kmer when using a threshold of 0.08. Trying with 0.04



── Regress each candidate kmer on sampled data

ℹ Running regression on 1 candidate kmers

• Bidirectional: TRUE

• Spat bin size: 40

• Number of spatial bins 11

• Length of sequence: 440

• Min gap: 0

• Max gap: 1

• Kmer length: 8

• Improve epsilon: 0.0001

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

→ regressing with seed: "CA*AGGGGC"

→ "CA*AGGGGC", score (r2): 0.00411995047021306, validation score (r2): 0.00236283758668099

ℹ Performing regression on full data

ℹ Using 11 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Motif is shorter than 15, extending with wildcards

ℹ Initializing regression with the following motif: "***CA*AGGGGC***"

ℹ Running regression

• Motif length: 15

• Bidirectional: TRUE

• Spat min: 30

• Spat max: 470

• Spat bin size: 40

• Number of bins: 11

• Improve epsilon: 0.0001

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

✔ Finished running regression. Consensus: "CA*AGGGKC**K"

✔ R^2: 0.0035

ℹ Best motif: "***CA*AGGGGC***", score (r2): 0.00236283758668099

ℹ KS statistic: 0.000557167967053048

ℹ KS test statistic for models 1 and 2: 0.39547414403972

ℹ Improvement in KS test statistic: 0.00234540411047895



── Running regression #3 ──



ℹ Using 11 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Performing sampled optimization

ℹ Sampling 1 of the dataset

✔ Sampled 5170 rows from the data frame.

ℹ Sampling 0.1 of the dataset

✔ Sampled 510 rows from the data frame.



── Generate candidate kmers

ℹ Could not find any kmer when using a threshold of 0.08. Trying with 0.04



── Regress each candidate kmer on sampled data

ℹ Running regression on 1 candidate kmers

• Bidirectional: TRUE

• Spat bin size: 40

• Number of spatial bins 11

• Length of sequence: 440

• Min gap: 0

• Max gap: 1

• Kmer length: 8

• Improve epsilon: 0.0001

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

→ regressing with seed: "CCAG*CTGG"

→ "CCAG*CTGG", score (r2): 0.00394711454899509, validation score (r2): 0.0138988716559824

ℹ Performing regression on full data

ℹ Using 11 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Motif is shorter than 15, extending with wildcards

ℹ Initializing regression with the following motif: "***CCAG*CTGG***"

ℹ Running regression

• Motif length: 15

• Bidirectional: TRUE

• Spat min: 30

• Spat max: 470

• Spat bin size: 40

• Number of bins: 11

• Improve epsilon: 0.0001

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

✔ Finished running regression. Consensus: "CAG*CTGG"

✔ R^2: 0.0056

ℹ Best motif: "***CCAG*CTGG***", score (r2): 0.0138988716559824

ℹ KS statistic: 0.117899796071434

ℹ KS test statistic for models 1, 2, and 3: 0.400569639459339

ℹ Improvement in KS test statistic: 0.00509549541961885



── Running regression #4 ──



ℹ Using 11 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Performing sampled optimization

ℹ Sampling 1 of the dataset

✔ Sampled 4880 rows from the data frame.

ℹ Sampling 0.1 of the dataset

✔ Sampled 480 rows from the data frame.



── Generate candidate kmers

ℹ Could not find any kmer when using a threshold of 0.08. Trying with 0.04



── Regress each candidate kmer on sampled data

ℹ Running regression on 1 candidate kmers

• Bidirectional: TRUE

• Spat bin size: 40

• Number of spatial bins 11

• Length of sequence: 440

• Min gap: 0

• Max gap: 1

• Kmer length: 8

• Improve epsilon: 0.0001

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

→ regressing with seed: "CTAAGTAC"

→ "CTAAGTAC", score (r2): 0.0000637429301837073, validation score (r2): 0.00040059539874464

ℹ Performing regression on full data

ℹ Using 11 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Motif is shorter than 15, extending with wildcards

ℹ Initializing regression with the following motif: "***CTAAGTAC****"

ℹ Running regression

• Motif length: 15

• Bidirectional: TRUE

• Spat min: 30

• Spat max: 470

• Spat bin size: 40

• Number of bins: 11

• Improve epsilon: 0.0001

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

✔ Finished running regression. Consensus: "CTAAGTAC"

✔ R^2: 0.0007

ℹ Best motif: "***CTAAGTAC****", score (r2): 0.00040059539874464

ℹ KS statistic: 0.154905883617376

ℹ KS test statistic for models 1, 2, 3, and 4: 0.402951023477989

ℹ Improvement in KS test statistic: 0.00238138401865035



── Running regression #5 ──



ℹ Using 11 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Performing sampled optimization

ℹ Sampling 1 of the dataset

✔ Sampled 5950 rows from the data frame.

ℹ Sampling 0.1 of the dataset

✔ Sampled 590 rows from the data frame.



── Generate candidate kmers

ℹ Could not find any kmer when using a threshold of 0.08. Trying with 0.04



── Regress each candidate kmer on sampled data

ℹ Running regression on 1 candidate kmers

• Bidirectional: TRUE

• Spat bin size: 40

• Number of spatial bins 11

• Length of sequence: 440

• Min gap: 0

• Max gap: 1

• Kmer length: 8

• Improve epsilon: 0.0001

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

→ regressing with seed: "CTAAGTAC"

→ "CTAAGTAC", score (r2): 0.00428250316078606, validation score (r2): 0.00000292520731291028

ℹ Performing regression on full data

ℹ Using 11 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Motif is shorter than 15, extending with wildcards

ℹ Initializing regression with the following motif: "***CTAAGTAC****"

ℹ Running regression

• Motif length: 15

• Bidirectional: TRUE

• Spat min: 30

• Spat max: 470

• Spat bin size: 40

• Number of bins: 11

• Improve epsilon: 0.0001

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

✔ Finished running regression. Consensus: "YCTAAGTAC"

✔ R^2: 0.0009

ℹ Best motif: "***CTAAGTAC****", score (r2): 0.00000292520731291028

ℹ KS statistic: 0.0924523986393347

ℹ KS test statistic for models 1, 2, 3, 4, and 5: 0.407298807815576

ℹ Improvement in KS test statistic: 0.00434778433758731

✔ Best model: model #1 (score of 0.393128739929241)

→ Saving the prego model to "/net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper/output/iq_5_pad_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg/prego_model.rds"

→ Regressing on train set

ℹ Number of peaks: 6354

→ Extracting sequences...

ℹ Calculating correlations between 21867 motif energies and ATAC difference...

ℹ Selected 2311 (out of 21867) features with absolute correlation >= 0.2

ℹ Running first round of regression, # of features: 2311

Warning message:
“glmnet.fit: algorithm did not converge”
ℹ Taking 2149 features with beta >= 0.01

ℹ Running second round of regression...

Warning message:
“glmnet.fit: algorithm did not converge”
ℹ Clustering 2114 features into 10 clusters...

ℹ Choosing top 10 features clusters

ℹ Features left: 2114

ℹ Learning a model for each motif cluster...

R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call

ℹ Infering energies...

ℹ Running final regression, number of features: 108

✔ Finished running model. Number of non-zero coefficients: 107 (out of 108). R^2: 0.219941922959597

→ Matching SCENIC.jaspar__MA1439.1

→ Matched with "HOMER.Mef2c", PSSM correlation = 0.619360446672042

→ Matching SCENIC.tfdimers__MD00201

→ Matched with "HOMER.SeqBias_A", PSSM correlation = 0.644361971634039

→ Matching SCENIC.swissregulon__mm__Otx2

→ Matched with "HOMER.GSC", PSSM correlation = 0.878738215939334

→ Matching SCENIC.neph__UW.Motif.0650

→ Matched with "HOMER.Klf4", PSSM correlation = 0.714586334279523

→ Matching JASPAR.PLAGL2

→ Matched with "HOMER.MyoG", PSSM correlation = 0.585036852325231

→ Matching HOCOMOCO.ZBT17_MOUSE.H11MO.0.A

→ Matched with "HOMER.Klf4", PSSM correlation = 0.841314670144191

→ Matching SCENIC.flyfactorsurvey__Six4_SOLEXA_FBgn0027364

→ Matched with "HOMER.Nkx6_1", PSSM correlation = 0.560687644936617

→ Matching SCENIC.predrem__nrMotif2497

→ Matched with "HOMER.E2F4", PSSM correlation = 0.617901104291784

→ Matching JASPAR.SPL4

→ Matched with "HOMER.Unknown2", PSSM correlation = 0.662489364060763

→ Matching HOCOMOCO.ZN770_HUMAN.H11MO.0.C

→ Matched with "HOMER.GSC", PSSM correlation = 0.538800446808731

ℹ Extracting sequences...

ℹ Computing motif energies for 1460 intervals and 7814 normalization intervals

ℹ Inferring the model on 1460 intervals



Number of motifs: 10

R^2 train: 0.22

R^2 test: 0.244



→ Saving the model to "/net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper/output/iq_5_pad_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg/iq_regression_model.rds"

ℹ Plotting 10 motifs

ℹ Plotting motif "GSC"

ℹ Plotting motif "MyoG"

ℹ Plotting motif "GSC.2"

ℹ Plotting motif "Nkx6_1"

ℹ Plotting motif "SeqBias_A"

ℹ Plotting motif "Klf4.2"

ℹ Plotting motif "Mef2c"

ℹ Plotting motif "E2F4"

ℹ Plotting motif "Klf4"

ℹ Plotting motif "Unknown2"

R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call

Warning message in ks.test.default(plot_df$observed[plot_df$energy == "0-3"], plot_df$observed[plot_df$energy == :
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(plot_df$observed[plot_df$energy == "0-3"], plot_df$observed[plot_df$energy == :
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(plot_df$observed[plot_df$energy == "0-3"], plot_df$observed[plot_df$energy == :
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(plot_df$observed[plot_df$energy == "0-3"], plot_df$observed[plot_df$energy == :
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(plot_df$observed[plot_df$energy == "0-3"], plot_df$observed[plot_df$energy == :
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(plot_df$observed[plot_df$energy == "0-3"], plot_df$observed[plot_df$energy == :
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(plot_df$observed[plot_df$energy == "0-3"], plot_df$observed[plot_df$energy == :
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(plot_df$observed[plot_df$energy == "0-3"], plot_df$observed[plot_df$energy == :
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(plot_df$observed[plot_df$energy == "0-3"], plot_df$observed[plot_df$energy == :
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(plot_df$observed[plot_df$energy == "0-3"], plot_df$observed[plot_df$energy == :
“p-value will be approximate in the presence of ties”
ℹ Saving plot...

Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
✔ Plot saved to /net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper/output/iq_5_pad_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg/iq_regression_model.pdf

→ Filtering the model

Warning message:
“glmnet.fit: algorithm did not converge”
ℹ Using 63 samples for filtering

ℹ R^2 of the full model: 0.0117434593033648

ℹ Filtering features with R^2 < 0.0005 and bits < 1.75

Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by Mef2c (----AAAATAA----): 0.00200146640230668. Bits: 5.79565711337425

Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by SeqBias_A (-A-AAAATAAAA---): -0.000229166919173266. Bits: 12.414041682169

Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by GSC.2 (----GATTA------): -0.0000582961178558997. Bits: 3.76702896947396

Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by Klf4.2 (----CC-CGC-----): -0.00126851572318711. Bits: 2.62321187210819

Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by MyoG (-------C-G-GG-C): 0.000879136821174416. Bits: 3.80463509250319

Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by Klf4 (----C-CGCCC----): -0.0146015504976287. Bits: 5.92074567643368

Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by Nkx6_1 (--------ATCA---): 0.00571995012429214. Bits: 3.11934206164853

Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by E2F4 (---GGAGCGGC----): 0.00252094779831745. Bits: 6.85524607607079

Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by Unknown2 (---AAC-GTAC----): -0.0165434636426548. Bits: 4.79507733397974

Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by GSC (-G-C-GA--T--T--): 0.00428766614358849. Bits: 3.76496716685512

ℹ Trying to remove the following features with R^2 < 0.0005: "SeqBias_A", "GSC.2", "Klf4.2", "Klf4", and "Unknown2"

Warning message:
“glmnet.fit: algorithm did not converge”
Warning message:
“glmnet.fit: algorithm did not converge”
→ Not removing "Klf4" (changed the R^2 by only 0.000821280801959725).

Warning message:
“glmnet.fit: algorithm did not converge”
→ Not removing "Klf4.2" (changed the R^2 by only 0.0109937729124703).

Warning message:
“glmnet.fit: algorithm did not converge”
→ Not removing "SeqBias_A" (changed the R^2 by only 0.00556016950194496).

Warning message:
“glmnet.fit: algorithm did not converge”
→ Removing "GSC.2" changed the R^2 by -0.000485818136000939

ℹ Removed 0 features with bits < 1.75

ℹ Removed 2 features with R^2 < 0.0005

✔ After filtering: Number of non-zero coefficients: 100 (out of 100). R^2: 0.217337613201876. Number of models: 8

ℹ Extracting sequences...

ℹ Computing motif energies for 1460 intervals and 7814 normalization intervals

ℹ Inferring the model on 1460 intervals



Number of motifs: 8

R^2 train: 0.217

R^2 test: 0.246



→ Saving the model to "/net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper/output/iq_5_pad_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg/iq_regression_filtered_model.rds"

ℹ Plotting 8 motifs

ℹ Plotting motif "Nkx6_1"

ℹ Plotting motif "GSC"

ℹ Plotting motif "E2F4"

ℹ Plotting motif "Mef2c"

ℹ Plotting motif "MyoG"

ℹ Plotting motif "SeqBias_A"

ℹ Plotting motif "Klf4.2"

ℹ Plotting motif "Klf4"

R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call

Warning message in ks.test.default(plot_df$observed[plot_df$energy == "0-3"], plot_df$observed[plot_df$energy == :
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(plot_df$observed[plot_df$energy == "0-3"], plot_df$observed[plot_df$energy == :
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(plot_df$observed[plot_df$energy == "0-3"], plot_df$observed[plot_df$energy == :
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(plot_df$observed[plot_df$energy == "0-3"], plot_df$observed[plot_df$energy == :
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(plot_df$observed[plot_df$energy == "0-3"], plot_df$observed[plot_df$energy == :
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(plot_df$observed[plot_df$energy == "0-3"], plot_df$observed[plot_df$energy == :
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(plot_df$observed[plot_df$energy == "0-3"], plot_df$observed[plot_df$energy == :
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(plot_df$observed[plot_df$energy == "0-3"], plot_df$observed[plot_df$energy == :
“p-value will be approximate in the presence of ties”
ℹ Saving plot...

Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
✔ Plot saved to /net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper/output/iq_5_pad_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg/iq_regression_filtered_model.pdf

✔ Finished IQ regression



Run `plot_traj_model_report(traj_model)` to visualize the model features

Run `plot_prediction_scatter(traj_model)` to visualize the model predictions

<TrajectoryModel> with 8 motifs and 17 additional features

Slots include:
• @model: A GLM model object. Number of non-zero coefficients: 100
• @motif_models: A named list of motif models. Each element contains PSSM and
spatial model (8 models: "Mef2c", "SeqBias_A", "Klf4.2", "MyoG", "Klf4",
"Nkx6_1", "E2F4", and "GSC")
• @additional_features: A data frame of additional features (17 features)
• @coefs: A data frame of coefficients (25 elements)
• @model_features: A matrix of the model features (logistic functions of the
motif models energies, dimensions: 7814x100)
• @normalized_energies: A matrix of normalized energies of the model features
(dimensions: 7814x8)
• @type: A vector the length of the number of peaks, indicating whether each
peak is a training ('train') or a prediction peak ('test')
• @diff_score: A numeric value representing the difference score the model was
trained on (7814 elements)
• @predicted_diff_score: A numeric value representing the predicted difference
score
• @initial_prego_models: A list of prego models used in the initial phase of
the algorithm (5 models)
• @peak_intervals: A data frame containing the peak intervals (7814 elements)
• @normalization_intervals: A data frame containing the intervals used for
energy normalization (7814 elements)
• @features_r2: A numeric vector of the added R^2 values for each feature (8
elements)
• @params: A list of parameters used for training (including:
"energy_norm_quantile", "norm_energy_max", "min_energy", "alpha", "lambda",
"peaks_size", "spat_num_bins", "spat_bin_size", "n_clust_factor",
"include_interactions", "interaction_threshold", "symmetrize_spat", "seed",
"names_map", "stats", "features_bits", "r2_threshold", and "bits_threshold")

R^2 train: 0.217
R^2 test: 0.246

→ Computing sequence features

ℹ Seed: 60427

ℹ Training on 6354 intervals (81%) and testing on 1460 intervals (19%)

ℹ Saving the train and test indices to "/net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper/output/iq_3_pad_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg"

ℹ Learning prego motifs (de-novo motifs)

ℹ Extracting sequences...

ℹ Inferring 5 prego motifs...

ℹ Using 11 bins of size 40 bp

ℹ Running regression for 5 motifs



── Running first regression ──



ℹ Using 11 bins of size 40 bp

ℹ Using "ks" as the final metric

ℹ Number of response variables: 1

ℹ Performing sampled optimization

ℹ Sampling 1 of the dataset

ℹ Stratified sampling

ℹ sampled 1973 zeros and 4381 ones

ℹ Sampling 0.1 of the dataset

ℹ Stratified sampling

ℹ sampled 197 zeros and 438 ones



── Generate candidate kmers



── Regress each candidate kmer on sampled data

ℹ Running regression on 3 candidate kmers

• Bidirectional: TRUE

• Spat bin size: 40

• Number of spatial bins 11

• Length of sequence: 440

• Min gap: 0

• Max gap: 1

• Kmer length: 8

• Improve epsilon: 0.0001

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call

ℹ Performing regression on full data

ℹ Using 11 bins of size 40 bp

ℹ Using "ks" as the final metric

ℹ Number of response variables: 1

ℹ Motif is shorter than 15, extending with wildcards

ℹ Initializing regression with the following motif: "***GA*GGGGAG***"

ℹ Running regression

• Motif length: 15

• Bidirectional: TRUE

• Spat min: 30

• Spat max: 470

• Spat bin size: 40

• Number of bins: 11

• Improve epsilon: 0.0001

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

✔ Finished running regression. Consensus: "S**M"

✔ KS test D: 0.001, p-value: 0.997208214742313

ℹ Best motif: "***GA*GGGGAG***", score (ks): 0.00228310502283103



── Running regression #2 ──



ℹ Using 11 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Performing sampled optimization

ℹ Sampling 1 of the dataset

✔ Sampled 5860 rows from the data frame.

ℹ Sampling 0.1 of the dataset

✔ Sampled 580 rows from the data frame.



── Generate candidate kmers

ℹ Could not find any kmer when using a threshold of 0.08. Trying with 0.04



── Regress each candidate kmer on sampled data

ℹ Running regression on 1 candidate kmers

• Bidirectional: TRUE

• Spat bin size: 40

• Number of spatial bins 11

• Length of sequence: 440

• Min gap: 0

• Max gap: 1

• Kmer length: 8

• Improve epsilon: 0.0001

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

→ regressing with seed: "AAAATA*AT"

→ "AAAATA*AT", score (r2): 0.0129838144529718, validation score (r2): 0.00984208339315275

ℹ Performing regression on full data

ℹ Using 11 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Motif is shorter than 15, extending with wildcards

ℹ Initializing regression with the following motif: "***AAAATA*AT***"

ℹ Running regression

• Motif length: 15

• Bidirectional: TRUE

• Spat min: 30

• Spat max: 470

• Spat bin size: 40

• Number of bins: 11

• Improve epsilon: 0.0001

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

✔ Finished running regression. Consensus: "A*AAT***T"

✔ R^2: 0.0155

ℹ Best motif: "***AAAATA*AT***", score (r2): 0.00984208339315275

ℹ KS statistic: 0.116606601815678

ℹ KS test statistic for models 1 and 2: 0.330425825105484

ℹ Improvement in KS test statistic: 0.32941214036144



── Running regression #3 ──



ℹ Using 11 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Performing sampled optimization

ℹ Sampling 1 of the dataset

✔ Sampled 4980 rows from the data frame.

ℹ Sampling 0.1 of the dataset

✔ Sampled 490 rows from the data frame.



── Generate candidate kmers

ℹ Could not find any kmer when using a threshold of 0.08. Trying with 0.04



── Regress each candidate kmer on sampled data

ℹ Running regression on 1 candidate kmers

• Bidirectional: TRUE

• Spat bin size: 40

• Number of spatial bins 11

• Length of sequence: 440

• Min gap: 0

• Max gap: 1

• Kmer length: 8

• Improve epsilon: 0.0001

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

→ regressing with seed: "GA*TGTGCA"

→ "GA*TGTGCA", score (r2): 0.00479900656457047, validation score (r2): 0.00333330085453378

ℹ Performing regression on full data

ℹ Using 11 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Motif is shorter than 15, extending with wildcards

ℹ Initializing regression with the following motif: "***GA*TGTGCA***"

ℹ Running regression

• Motif length: 15

• Bidirectional: TRUE

• Spat min: 30

• Spat max: 470

• Spat bin size: 40

• Number of bins: 11

• Improve epsilon: 0.0001

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

✔ Finished running regression. Consensus: "G**TGTGCA"

✔ R^2: 0.0048

ℹ Best motif: "***GA*TGTGCA***", score (r2): 0.00333330085453378

ℹ KS statistic: 0.00179911109959343

ℹ KS test statistic for models 1, 2, and 3: 0.339982250683242

ℹ Improvement in KS test statistic: 0.00955642557775804



── Running regression #4 ──



ℹ Using 11 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Performing sampled optimization

ℹ Sampling 1 of the dataset

✔ Sampled 5760 rows from the data frame.

ℹ Sampling 0.1 of the dataset

✔ Sampled 570 rows from the data frame.



── Generate candidate kmers

ℹ Could not find any kmer when using a threshold of 0.08. Trying with 0.04



── Regress each candidate kmer on sampled data

ℹ Running regression on 1 candidate kmers

• Bidirectional: TRUE

• Spat bin size: 40

• Number of spatial bins 11

• Length of sequence: 440

• Min gap: 0

• Max gap: 1

• Kmer length: 8

• Improve epsilon: 0.0001

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

→ regressing with seed: "CCTCCTAG"

→ "CCTCCTAG", score (r2): 0.011535485762436, validation score (r2): 0.00128004852667894

ℹ Performing regression on full data

ℹ Using 11 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Motif is shorter than 15, extending with wildcards

ℹ Initializing regression with the following motif: "***CCTCCTAG****"

ℹ Running regression

• Motif length: 15

• Bidirectional: TRUE

• Spat min: 30

• Spat max: 470

• Spat bin size: 40

• Number of bins: 11

• Improve epsilon: 0.0001

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

✔ Finished running regression. Consensus: "CCTCCT*K"

✔ R^2: 0.0088

ℹ Best motif: "***CCTCCTAG****", score (r2): 0.00128004852667894

ℹ KS statistic: 0.0015205271160669

ℹ KS test statistic for models 1, 2, 3, and 4: 0.344608503313333

ℹ Improvement in KS test statistic: 0.00462625263009081



── Running regression #5 ──



ℹ Using 11 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Performing sampled optimization

ℹ Sampling 1 of the dataset

✔ Sampled 5770 rows from the data frame.

ℹ Sampling 0.1 of the dataset

✔ Sampled 570 rows from the data frame.



── Generate candidate kmers

ℹ Could not find any kmer when using a threshold of 0.08. Trying with 0.04



── Regress each candidate kmer on sampled data

ℹ Running regression on 1 candidate kmers

• Bidirectional: TRUE

• Spat bin size: 40

• Number of spatial bins 11

• Length of sequence: 440

• Min gap: 0

• Max gap: 1

• Kmer length: 8

• Improve epsilon: 0.0001

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

→ regressing with seed: "CCTGG*TGC"

→ "CCTGG*TGC", score (r2): 0.013475532699097, validation score (r2): 0.000124080551184761

ℹ Performing regression on full data

ℹ Using 11 bins of size 40 bp

ℹ Using "r2" as the final metric

ℹ Number of response variables: 1

ℹ Motif is shorter than 15, extending with wildcards

ℹ Initializing regression with the following motif: "***CCTGG*TGC***"

ℹ Running regression

• Motif length: 15

• Bidirectional: TRUE

• Spat min: 30

• Spat max: 470

• Spat bin size: 40

• Number of bins: 11

• Improve epsilon: 0.0001

• Min nuc prob: 0.001

• Uniform prior: 0.05

• Score metric: "r2"

• Seed: 60427

✔ Finished running regression. Consensus: "CC*GG*TGC"

✔ R^2: 0.0068

ℹ Best motif: "***CCTGG*TGC***", score (r2): 0.000124080551184761

ℹ KS statistic: 0.0010136847440446

ℹ KS test statistic for models 1, 2, 3, 4, and 5: 0.358075863925607

ℹ Improvement in KS test statistic: 0.0134673606122739

✔ Best model: model #2 (score of 0.116606601815678)

→ Saving the prego model to "/net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper/output/iq_3_pad_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg/prego_model.rds"

→ Regressing on train set

ℹ Number of peaks: 6354

→ Extracting sequences...

ℹ Calculating correlations between 21867 motif energies and ATAC difference...

ℹ Selected 223 (out of 21867) features with absolute correlation >= 0.2

ℹ Running first round of regression, # of features: 223

ℹ Taking 183 features with beta >= 0.01

ℹ Running second round of regression...

ℹ Clustering 183 features into 10 clusters...

ℹ Choosing top 10 features clusters

ℹ Features left: 183

ℹ Learning a model for each motif cluster...

R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call

ℹ Infering energies...

ℹ Running final regression, number of features: 108

✔ Finished running model. Number of non-zero coefficients: 107 (out of 108). R^2: 0.258395854254954

→ Matching SCENIC.cisbp__M01050

→ Matched with "HOMER.TCFL2", PSSM correlation = 0.52739306175118

→ Matching SCENIC.homer__GGGGGGGG_Maz

→ Matched with "HOMER.Egr1", PSSM correlation = 0.600683575607317

→ Matching SCENIC.cisbp__M02363

→ Matched with "HOMER.Maz", PSSM correlation = 0.684830270210646

→ Matching SCENIC.cisbp__M00596

→ Matched with "HOMER.ZNF711", PSSM correlation = 0.530874662525828

→ Matching SCENIC.yetfasco__YGL181W_694

→ Matched with "HOMER.CRE", PSSM correlation = 0.459651703958793

→ Matching HOMER.NRF1

→ Matched with "HOMER.NRF1", PSSM correlation = 0.594761840360188

→ Matching SCENIC.cisbp__M01350

→ Matched with "HOMER.MafA", PSSM correlation = 0.587102641026766

→ Matching SCENIC.predrem__nrMotif1968

→ Matched with "HOMER.Ascl1", PSSM correlation = 0.583594149787116

→ Matching SCENIC.predrem__nrMotif2653

→ Matched with "HOMER.DPL_1", PSSM correlation = 0.63065258303276

→ Matching e5

→ Matched with "HOMER.HIF_1b", PSSM correlation = 0.519651064778363

ℹ Extracting sequences...

ℹ Computing motif energies for 1460 intervals and 7814 normalization intervals

ℹ Inferring the model on 1460 intervals



Number of motifs: 10

R^2 train: 0.258

R^2 test: 0.246



→ Saving the model to "/net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper/output/iq_3_pad_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg/iq_regression_model.rds"

ℹ Plotting 10 motifs

ℹ Plotting motif "TCFL2"

ℹ Plotting motif "ZNF711"

ℹ Plotting motif "DPL_1"

ℹ Plotting motif "CRE"

ℹ Plotting motif "Ascl1"

ℹ Plotting motif "MafA"

ℹ Plotting motif "Egr1"

ℹ Plotting motif "NRF1"

ℹ Plotting motif "Maz"

ℹ Plotting motif "HIF_1b"

R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call

Warning message in ks.test.default(plot_df$observed[plot_df$energy == "0-3"], plot_df$observed[plot_df$energy == :
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(plot_df$observed[plot_df$energy == "0-3"], plot_df$observed[plot_df$energy == :
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(plot_df$observed[plot_df$energy == "0-3"], plot_df$observed[plot_df$energy == :
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(plot_df$observed[plot_df$energy == "0-3"], plot_df$observed[plot_df$energy == :
“p-value will be approximate in the presence of ties”
ℹ Saving plot...

Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 32 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
✔ Plot saved to /net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper/output/iq_3_pad_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg/iq_regression_model.pdf

→ Filtering the model

Warning message:
“glmnet.fit: algorithm did not converge”
ℹ Using 63 samples for filtering

ℹ R^2 of the full model: 0.0376728055939286

ℹ Filtering features with R^2 < 0.0005 and bits < 1.75

Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by TCFL2 (------C--G-GAG-): 0.00198695390757279. Bits: 2.73843759438911

Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by Egr1 (------TAGGG----): -0.000924147112232168. Bits: 5.14294565034108

→ R^2 added by Maz (A---GGGCGCG----): -0.000608067939373201. Bits: 5.80443474783653

Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by ZNF711 (----GA---------): 0.00538715366654987. Bits: 1.26170374895418

Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by CRE (---------------): 0.00211469822496432. Bits: 0.440577571468998

Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by NRF1 (---CGCAGGCGC---): 0.0120380874625233. Bits: 4.45345287204138

Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by MafA (----CCGCGGA----): 0.00342600623159271. Bits: 4.45230917518863

→ R^2 added by Ascl1 (GCGCAGAG): 0.00069146607588242. Bits: 11.330852761214

Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by DPL_1 (-----GAGC-G----): 0.00916299641048248. Bits: 3.08224826739621

Warning message:
“glmnet.fit: algorithm did not converge”
→ R^2 added by HIF_1b (---GCATCCAGG---): 0.0122661106692315. Bits: 7.39266891217156

ℹ Removing the following features with bits < 1.75: "ZNF711" and "CRE"

ℹ Trying to remove the following features with R^2 < 0.0005: "Egr1" and "Maz"

Warning message:
“glmnet.fit: algorithm did not converge”
Warning message:
“glmnet.fit: algorithm did not converge”
→ Removing "Maz" changed the R^2 by -0.00832371577671058

ℹ Removed 2 features with bits < 1.75

ℹ Removed 2 features with R^2 < 0.0005

✔ After filtering: Number of non-zero coefficients: 92 (out of 92). R^2: 0.246931695771702. Number of models: 6

ℹ Extracting sequences...

ℹ Computing motif energies for 1460 intervals and 7814 normalization intervals

ℹ Inferring the model on 1460 intervals



Number of motifs: 6

R^2 train: 0.247

R^2 test: 0.226



→ Saving the model to "/net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper/output/iq_3_pad_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg/iq_regression_filtered_model.rds"

ℹ Plotting 6 motifs

ℹ Plotting motif "HIF_1b"

ℹ Plotting motif "NRF1"

ℹ Plotting motif "DPL_1"

ℹ Plotting motif "MafA"

ℹ Plotting motif "TCFL2"

ℹ Plotting motif "Ascl1"

R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call
R_zmq_msg_send errno: 4 strerror: Interrupted system call

Warning message in ks.test.default(plot_df$observed[plot_df$energy == "0-3"], plot_df$observed[plot_df$energy == :
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(plot_df$observed[plot_df$energy == "0-3"], plot_df$observed[plot_df$energy == :
“p-value will be approximate in the presence of ties”
ℹ Saving plot...

Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 46 rows containing missing values or values outside the scale range
(`geom_line()`).”
Warning message:
“Removed 32 rows containing missing values or values outside the scale range
(`geom_line()`).”
✔ Plot saved to /net/mraid20/ifs/wisdom/tanay_lab/tgdata/users/evghenic/Proj/polycomb/seq2epi_paper/output/iq_3_pad_prego_10_motifs_no_add_oriented_hg19_pcg_vs_txg/iq_regression_filtered_model.pdf

✔ Finished IQ regression



Run `plot_traj_model_report(traj_model)` to visualize the model features

Run `plot_prediction_scatter(traj_model)` to visualize the model predictions

<TrajectoryModel> with 6 motifs and 17 additional features

Slots include:
• @model: A GLM model object. Number of non-zero coefficients: 92
• @motif_models: A named list of motif models. Each element contains PSSM and
spatial model (6 models: "TCFL2", "NRF1", "MafA", "Ascl1", "DPL_1", and
"HIF_1b")
• @additional_features: A data frame of additional features (17 features)
• @coefs: A data frame of coefficients (23 elements)
• @model_features: A matrix of the model features (logistic functions of the
motif models energies, dimensions: 7814x92)
• @normalized_energies: A matrix of normalized energies of the model features
(dimensions: 7814x6)
• @type: A vector the length of the number of peaks, indicating whether each
peak is a training ('train') or a prediction peak ('test')
• @diff_score: A numeric value representing the difference score the model was
trained on (7814 elements)
• @predicted_diff_score: A numeric value representing the predicted difference
score
• @initial_prego_models: A list of prego models used in the initial phase of
the algorithm (5 models)
• @peak_intervals: A data frame containing the peak intervals (7814 elements)
• @normalization_intervals: A data frame containing the intervals used for
energy normalization (7814 elements)
• @features_r2: A numeric vector of the added R^2 values for each feature (6
elements)
• @params: A list of parameters used for training (including:
"energy_norm_quantile", "norm_energy_max", "min_energy", "alpha", "lambda",
"peaks_size", "spat_num_bins", "spat_bin_size", "n_clust_factor",
"include_interactions", "interaction_threshold", "symmetrize_spat", "seed",
"names_map", "stats", "features_bits", "r2_threshold", and "bits_threshold")

R^2 train: 0.247
R^2 test: 0.226